using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Catchy.SourceGenerator
{
    [Generator]
    public sealed partial class CatchyIncrementalGenerator : IIncrementalGenerator
    {

        private static void EmitAssertable(SourceProductionContext spc, AssertableModel model)
        {
            EmitAssertableAssertionsClass(spc, model);
            EmitAsserterExtensions(spc, model);

            if (model.Fields.Length > 0)
            {
                EmitFieldAssertions(spc, model);
            }

            if (model.CrossTypes.Any(ct => ct.IsResolved && ct.RegisterInGlobalRegistry && ct.FieldMaps.Length > 0))
            {
                EmitCrossTypeDeepEqualRuleRegistration(spc, model);
            }
        }

        private static void EmitCrossTypeDeepEqualRuleRegistration(SourceProductionContext spc, AssertableModel model)
        {
            var applicable = model.CrossTypes
                .Where(ct => ct.IsResolved && ct.RegisterInGlobalRegistry && ct.FieldMaps.Length > 0)
                .ToArray();

            if (applicable.Length == 0)
            {
                return;
            }

            var className = $"CrossTypeRules_{SanitizeName(model.FullTypeName)}";

            var sb = new StringBuilder();
            sb.Append($$"""
                // <auto-generated/>
                #nullable enable
                using System.Collections.Generic;
                using System.Runtime.CompilerServices;

                namespace Catchy.Generated
                {
                    internal static class {{className}}
                    {
                        private sealed class StringComparisonObjectComparer : IEqualityComparer<object?>
                        {
                            private readonly global::System.StringComparison _comparison;
                            public StringComparisonObjectComparer(global::System.StringComparison comparison) => _comparison = comparison;
                            public new bool Equals(object? x, object? y)
                            {
                                if (x is string sx && y is string sy)
                                {
                                    return string.Equals(sx, sy, _comparison);
                                }
                                return object.Equals(x, y);
                            }
                            public int GetHashCode(object? obj) => obj?.GetHashCode() ?? 0;
                        }

                        [ModuleInitializer]
                        internal static void Register()
                        {

                """);

            foreach (var cross in applicable)
            {
                sb.AppendLine($"            if (!global::Catchy.Sdk.DeepEqualRuleRegistry.HasRule<{model.FullTypeName}, {cross.TargetTypeFullName}>())");
                sb.AppendLine("            {");
                sb.AppendLine($"                var rule = global::Catchy.DeepEqualRule.For<{model.FullTypeName}, {cross.TargetTypeFullName}>(disableReflection: true);");

                foreach (var map in cross.FieldMaps)
                {
                    var isStringMap = IsStringTypeName(map.SourceMemberType) && IsStringTypeName(map.TargetMemberType) && map.UseStringComparison;
                    if (isStringMap)
                    {
                        sb.AppendLine($"                rule = rule.Match<object?>(s => (object?)s.{map.SourceMemberName}, t => (object?)t.{map.TargetMemberName}, comparer: new StringComparisonObjectComparer({map.StringComparisonExpression}), name: \"{map.SourceMemberName}->{map.TargetMemberName}\");");
                    }
                    else
                    {
                        sb.AppendLine($"                rule = rule.Match<object?>(s => (object?)s.{map.SourceMemberName}, t => (object?)t.{map.TargetMemberName}, comparer: null, name: \"{map.SourceMemberName}->{map.TargetMemberName}\");");
                    }
                }

                sb.AppendLine("                rule.Register();");
                sb.AppendLine("            }");
            }

            sb.Append("""
                        }
                    }
                }

                """);

            var hint = $"CrossTypeRules_{SanitizeName(model.FullTypeName)}.g.cs";
            spc.AddSource(hint, SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        private static bool IsStringTypeName(string typeName)
            => typeName == "string"
               || typeName == "System.String"
               || typeName == "global::System.String";

        private static string EnsureGlobalQualification(string typeName)
            => typeName.StartsWith("global::", StringComparison.Ordinal) ? typeName : $"global::{typeName}";

        private static string GetAssertableAssertionsClassName(AssertableModel model)
            => $"{GetTypeName(model.TypeName)}Assertions";

        /// <summary>
        /// Resolves the fully-qualified base type string for the generated assertions class.
        /// <list type="bullet">
        ///   <item>null (default) → <c>ValueAssertions&lt;TValue&gt;</c></item>
        ///   <item>unbound open generic with any arity (e.g. <c>Foo&lt;&gt;</c>, <c>Foo&lt;,&gt;</c>, <c>Foo&lt;,,&gt;</c>)
        ///     → first type arg is substituted with TValue, remaining args are left as open type parameters
        ///     (e.g. <c>Foo&lt;TValue, T2&gt;</c> becomes <c>Foo&lt;TMyType, T2&gt;</c> — not supported for multi-T; emit a diagnostic instead)</item>
        ///   <item>concrete or already-closed generic → use verbatim</item>
        /// </list>
        /// When an unbound generic has arity &gt; 1 we cannot safely close it — the type name is emitted
        /// verbatim (which will produce a compile error in the generated file, surfacing the problem to the user).
        /// </summary>
        private static string GetAssertableBaseType(AssertableModel model)
        {
            if (model.BaseAssertionTypeName is null)
                return $"global::Catchy.ValueAssertions<{model.FullTypeName}>";

            var name = model.BaseAssertionTypeName;

            // Detect unbound open generic: ends with > and contains only commas (and whitespace) inside last <>
            var lastOpen = name.LastIndexOf('<');
            if (lastOpen >= 0)
            {
                var inside = name.Substring(lastOpen + 1, name.Length - lastOpen - 2); // strip < >
                var isUnbound = inside.Length == 0 || IsAllCommasAndWhitespace(inside);
                if (isUnbound)
                {
                    var arity = inside.Length == 0 ? 1 : inside.Split(',').Length;
                    var openName = name.Substring(0, lastOpen);
                    if (arity == 1)
                    {
                        // Simple case: single type parameter — substitute TValue
                        return $"{openName}<{model.FullTypeName}>";
                    }
                    // Multi-T: substitute first arg with TValue, leave rest as named placeholders
                    // e.g. Foo<,> → Foo<TMyType, T2>  (will compile only if the type has matching params)
                    var args = new string[arity];
                    args[0] = model.FullTypeName;
                    for (int i = 1; i < arity; i++)
                        args[i] = $"T{i + 1}";
                    return $"{openName}<{string.Join(", ", args)}>";
                }
            }

            // Concrete or already-closed generic — use verbatim
            return name;
        }

        private static bool IsAllCommasAndWhitespace(string s)
            => s.All(c => c == ',' || c == ' ');

        // Generator convention: all generated assertable constructors use (pipeline, value) order.
        private const string AssertableBaseArguments = "pipeline, value";

        private static void EmitAssertableAssertionsClass(SourceProductionContext spc, AssertableModel model)
        {
            var ns = string.IsNullOrEmpty(model.Namespace) ? "Catchy" : model.Namespace;
            var className = GetAssertableAssertionsClassName(model);
            var baseType = GetAssertableBaseType(model);
            var markerInterfaces = model.MarkerInterfaces.Length > 0
                ? ", " + string.Join(", ", model.MarkerInterfaces)
                : string.Empty;

            var code = $$"""
                // <auto-generated/>
                #nullable enable
                using System.Diagnostics;
                using Catchy.Sdk;

                namespace {{ns}}
                {
                    public sealed class {{className}}(global::Catchy.Sdk.AssertionPipeline pipeline, {{model.FullTypeName}} value)
                        : {{baseType}}({{AssertableBaseArguments}}){{markerInterfaces}}
                    {
                    }
                }

                """;

            var hint = $"AssertableType_{SanitizeName(model.FullTypeName)}.g.cs";
            spc.AddSource(hint, SourceText.From(code, Encoding.UTF8));
        }

        private static void EmitAsserterExtensions(SourceProductionContext spc, AssertableModel model)
        {
            var ns = string.IsNullOrEmpty(model.Namespace) ? "Catchy" : model.Namespace;
            var thatMethod = EmitThatEntryPoint(model.FullTypeName, GetAssertableAssertionsClassName(model));

            var code = $$"""
                // <auto-generated/>
                #nullable enable
                using System.Collections.Generic;
                using System.Runtime.CompilerServices;
                using Catchy.Sdk;

                namespace {{ns}}
                {
                    public static partial class AsserterExtensions
                    {
                {{thatMethod}}    }
                }

                """;

            var hint = $"Assertable_{SanitizeName(model.FullTypeName)}.g.cs";
            spc.AddSource(hint, SourceText.From(code, Encoding.UTF8));
        }


        private static void EmitFieldAssertions(SourceProductionContext spc, AssertableModel model)
        {
            var ns = string.IsNullOrEmpty(model.Namespace) ? "Catchy" : model.Namespace;

            var sb = new StringBuilder();
            sb.Append($$"""
                // <auto-generated/>
                #nullable enable
                using System.Diagnostics;
                using Catchy.Sdk;

                namespace {{ns}}
                {
                    public static partial class {{model.TypeName}}FieldAssertions
                    {

                """);

            foreach (var field in model.Fields.Where(f => !f.Skip))
            {
                EmitFieldAssertionMethods(sb, model.FullTypeName, field);
                EmitTransitionExtensionMethod(sb, model.FullTypeName, field);
            }

            sb.Append("""
                    }
                }

                """);

            var hint = $"FieldAssertions_{SanitizeName(model.FullTypeName)}.g.cs";
            spc.AddSource(hint, SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        private static void EmitTransitionExtensionMethod(StringBuilder sb, string fullTypeName, AssertableFieldModel field)
        {
            var receiverType = $"global::Catchy.ValueAssertions<{fullTypeName}>";

            // Default: ValueAssertions<T>. Override only when TransitionType is explicitly specified on [AssertMember].
            string returnType;
            string factory;
            if (field.TransitionTypeName is not null)
            {
                returnType = ResolveTransitionReturnType(field.TransitionTypeName, field.PropertyType);
                factory = $"new {returnType}(a.GetPipeline(), a.GetValue() is {{ }} __v ? __v.{field.PropertyName} : default!)";
            }
            else
            {
                returnType = $"global::Catchy.ValueAssertions<{field.PropertyType}>";
                factory = $"new global::Catchy.ValueAssertions<{field.PropertyType}>(a.GetPipeline(), a.GetValue() is {{ }} __v ? __v.{field.PropertyName} : default!)";
            }

            sb.Append($$"""
                        [DebuggerHidden, StackTraceHidden, global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                        public static {{returnType}} {{field.PropertyName}}(
                            this {{receiverType}} a)
                        {
                            a.Link("{{field.PropertyName}}");
                            return {{factory}};
                        }


                """);
        }

        /// <summary>
        /// Resolves the return type for a transition method from a user-supplied <c>TransitionType</c>.
        /// Handles unbound open generics (arity 1: close with TValue; arity &gt; 1: first arg = TValue, rest placeholders).
        /// Concrete or already-closed generics are used verbatim.
        /// </summary>
        private static string ResolveTransitionReturnType(string transitionTypeName, string propertyType)
        {
            var lastOpen = transitionTypeName.LastIndexOf('<');
            if (lastOpen >= 0)
            {
                var inside = transitionTypeName.Substring(lastOpen + 1, transitionTypeName.Length - lastOpen - 2);
                if (inside.Length == 0 || IsAllCommasAndWhitespace(inside))
                {
                    var arity = inside.Length == 0 ? 1 : inside.Split(',').Length;
                    var openName = transitionTypeName.Substring(0, lastOpen);
                    if (arity == 1)
                        return $"{openName}<{propertyType}>";
                    var args = new string[arity];
                    args[0] = propertyType;
                    for (int i = 1; i < arity; i++)
                        args[i] = $"T{i + 1}";
                    return $"{openName}<{string.Join(", ", args)}>";
                }
            }
            return transitionTypeName;
        }

        private static void EmitFieldAssertionMethods(StringBuilder sb, string fullTypeName, AssertableFieldModel field)
        {
            var methodBaseName = $"Has{field.PropertyName}";
            var fieldAccessor = $"v.{field.PropertyName}";
            var fieldType = field.PropertyType;
            var receiverType = $"global::Catchy.ValueAssertions<{fullTypeName}>";

            sb.Append($$"""
                        [DebuggerHidden, StackTraceHidden, AssertionMethod]
                        public static {{receiverType}} {{methodBaseName}}(
                            this {{receiverType}} a, {{fieldType}} expected)
                        {
                            a.Link("{{methodBaseName}}");
                            a.Op(CheckOperation.Sync(
                                () =>
                                {
                                    var v = a.GetValue();
                                    return v is not null && global::System.Collections.Generic.EqualityComparer<{{fieldType}}>.Default.Equals({{fieldAccessor}}, expected);
                                },
                                () => $"Expected {a.GetValue()} to have {{field.PropertyName}} = {expected}",
                                a.IsSkipped()));
                            return a;
                        }


                """);

            if (IsStringType(fieldType))
            {
                sb.Append($$"""
                        [DebuggerHidden, StackTraceHidden, AssertionMethod]
                        public static {{receiverType}} {{methodBaseName}}Contains(
                            this {{receiverType}} a, string expectedPart)
                        {
                            a.Link("{{methodBaseName}}Contains");
                            a.Op(CheckOperation.Sync(
                                () =>
                                {
                                    var v = a.GetValue();
                                    return v is not null && {{fieldAccessor}} is not null && {{fieldAccessor}}.IndexOf(expectedPart, global::System.StringComparison.Ordinal) >= 0;
                                },
                                () => $"Expected {a.GetValue()} to have {{field.PropertyName}} containing {expectedPart}",
                                a.IsSkipped()));
                            return a;
                        }


                """);
            }

            if (IsNumericType(fieldType))
            {
                sb.Append($$"""
                        [DebuggerHidden, StackTraceHidden, AssertionMethod]
                        public static {{receiverType}} {{methodBaseName}}GreaterThan(
                            this {{receiverType}} a, {{fieldType}} min)
                        {
                            a.Link("{{methodBaseName}}GreaterThan");
                            a.Op(CheckOperation.Sync(
                                () =>
                                {
                                    var v = a.GetValue();
                                    return v is not null && {{fieldAccessor}} > min;
                                },
                                () => $"Expected {a.GetValue()} to have {{field.PropertyName}} > {min}",
                                a.IsSkipped()));
                            return a;
                        }


                """);
            }
        }

        private static bool IsStringType(string fieldType)
            => fieldType == "string" || fieldType == "string?" || fieldType.EndsWith(".String", StringComparison.Ordinal) || fieldType.EndsWith(".String?", StringComparison.Ordinal);

        private static bool IsNumericType(string fieldType)
        {
            return fieldType.Contains("int") || fieldType.Contains("long") || fieldType.Contains("short")
                || fieldType.Contains("byte") || fieldType.Contains("double") || fieldType.Contains("float")
                || fieldType.Contains("decimal") || fieldType.Contains("Int") || fieldType.Contains("Long")
                || fieldType.Contains("Double") || fieldType.Contains("Float") || fieldType.Contains("Decimal");
        }

        private static string EmitThatEntryPoint(string fullTypeName, string assertionClassName)
        {
            var summary = $"Starts assertions for {GetTypeName(fullTypeName)}.";
            return $$"""
                        /// <summary>
                        /// {{summary}}
                        /// </summary>
                        public static {{assertionClassName}} That(
                            this global::Catchy.Asserter a, {{fullTypeName}} value,
                            [CallerArgumentExpression(nameof(a))]     string? aExpr = null,
                            [CallerArgumentExpression(nameof(value))] string? vExpr = null,
                            [CallerFilePath]      string? file   = null,
                            [CallerLineNumber] int      line   = 0,
                            [CallerMemberName]      string? member = null)
                        {
                            var p = a.NewPipeline(asserterExpr: aExpr, methodName: "That", valueExpr: vExpr, file: file, line: line, member: member);
                            return new {{assertionClassName}}(p, value);
                        }

                """;
        }



        private sealed record AssertionMethodModel(
            string MethodName,
            string ExpectationMessage,
            bool IsAsync,
            ImmutableArray<ParamModel> Parameters);

        private sealed record ParamModel(string Type, string Name);

        private sealed record AssertForTargetModel(
            string TargetTypeName,
            string TargetTypeFullName,
            GeneratedMode Mode);

        private enum GeneratedMode
        {
            EntryPoint = 0,
            ExtensionsOnly = 1
        }

        private sealed record AssertForModel(
            string Namespace,
            string ContainerClassName,
            ImmutableArray<AssertForTargetModel> Targets,
            ImmutableArray<AssertionMethodModel> Methods);

        private static AssertForModel? GetAssertForModel(
            GeneratorSyntaxContext ctx, System.Threading.CancellationToken ct)
        {
            if (ctx.Node is not ClassDeclarationSyntax)
            {
                return null;
            }

            if (ctx.SemanticModel.GetDeclaredSymbol(ctx.Node, ct) is not INamedTypeSymbol containerType)
            {
                return null;
            }

            ct.ThrowIfCancellationRequested();

            var targets = ExtractAssertForTargets(containerType);
            if (targets.Length == 0)
            {
                return null;
            }

            var methods = ImmutableArray.CreateBuilder<AssertionMethodModel>();

            foreach (var member in containerType.GetMembers().OfType<IMethodSymbol>())
            {
                if (!member.IsStatic)
                {
                    continue;
                }

                var assertionAttr = member.GetAttributes()
                    .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == "Catchy.AssertionAttribute");
                if (assertionAttr is null) continue;

                var message = assertionAttr.ConstructorArguments.FirstOrDefault().Value?.ToString() ?? member.Name;
                bool isAsync = member.ReturnType.ToDisplayString().StartsWith("System.Threading.Tasks.Task", StringComparison.Ordinal);

                var extraParams = member.Parameters.Skip(1)
                    .Select(p => new ParamModel(p.Type.ToDisplayString(), p.Name))
                    .ToImmutableArray();

                methods.Add(new AssertionMethodModel(member.Name, message, isAsync, extraParams));
            }

            var ns = containerType.ContainingNamespace?.IsGlobalNamespace == false
                ? containerType.ContainingNamespace.ToDisplayString()
                : "";

            return new AssertForModel(
                ns,
                containerType.Name,
                targets,
                methods.ToImmutable());
        }

        private static ImmutableArray<AssertForTargetModel> ExtractAssertForTargets(INamedTypeSymbol containerType)
        {
            var targets = ImmutableArray.CreateBuilder<AssertForTargetModel>();

            foreach (var attr in containerType.GetAttributes())
            {
                var attrClass = attr.AttributeClass;
                if (attrClass is null)
                {
                    continue;
                }

                if (attrClass.OriginalDefinition.ToDisplayString() == "Catchy.AssertForAttribute<T>")
                {
                    if (attrClass.TypeArguments.FirstOrDefault() is ITypeSymbol targetType)
                    {
                        AddAssertForTarget(targets, targetType, attr);
                    }

                    continue;
                }

                if (attrClass.ToDisplayString() != "Catchy.AssertForAttribute")
                {
                    continue;
                }

                foreach (var ctorArg in attr.ConstructorArguments)
                {
                    if (ctorArg.Kind != TypedConstantKind.Array)
                    {
                        continue;
                    }

                    foreach (var value in ctorArg.Values)
                    {
                        if (value.Value is ITypeSymbol targetType)
                        {
                            AddAssertForTarget(targets, targetType, attr);
                        }
                    }
                }
            }

            return [.. targets
                .GroupBy(t => t.TargetTypeFullName, StringComparer.Ordinal)
                .Select(g => g.First())];
        }

        private static void AddAssertForTarget(
            ImmutableArray<AssertForTargetModel>.Builder targets,
            ITypeSymbol targetType,
            AttributeData attribute)
        {
            var fullTarget = GetAssertForAssertionValueType(targetType);
            var targetName = SanitizeName(targetType.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat));
            var mode = GeneratedMode.EntryPoint;

            foreach (var named in attribute.NamedArguments)
            {
                switch (named.Key)
                {
                    case "Mode" when named.Value.Value is int modeValue:
                        mode = (GeneratedMode)modeValue;
                        break;
                    }
            }

            targets.Add(new AssertForTargetModel(targetName, fullTarget, mode));
        }

        private static string GetAssertForAssertionValueType(ITypeSymbol targetType)
        {
            var fullTarget = EnsureGlobalQualification(targetType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
            return targetType.IsReferenceType && !fullTarget.EndsWith("?", StringComparison.Ordinal)
                ? fullTarget + "?"
                : fullTarget;
        }

        private static void EmitAssertFor(SourceProductionContext spc, AssertForModel model)
        {
            foreach (var target in model.Targets)
            {
                var assertionsClass = $"{model.ContainerClassName}_{target.TargetTypeName}Stateless";
                var fullTarget = target.TargetTypeFullName;
                var ns = string.IsNullOrEmpty(model.Namespace) ? "Catchy" : model.Namespace;

                var sb = new StringBuilder();
                sb.Append($$"""
                    // <auto-generated/>
                    #nullable enable
                    using System;
                    using System.Diagnostics;
                    using System.Runtime.CompilerServices;
                    using Catchy.Sdk;

                    namespace {{ns}}
                    {

                    """);

                if (target.Mode == GeneratedMode.EntryPoint)
                {
                    sb.Append($$"""
                            public sealed class {{assertionsClass}}
                                : global::Catchy.ValueAssertions<{{fullTarget}}>
                            {
                                internal {{assertionsClass}}({{fullTarget}} value, global::Catchy.Sdk.AssertionPipeline pipeline)
                                    : base(pipeline, value) { }
                            }

                            public static partial class AsserterExtensions
                            {
                                public static {{assertionsClass}} That(
                                    this global::Catchy.Asserter a, {{fullTarget}} value,
                                    [CallerArgumentExpression(nameof(a))]     string? aExpr = null,
                                    [CallerArgumentExpression(nameof(value))] string? vExpr = null,
                                    [CallerFilePath]      string? file = null,
                                    [CallerLineNumber] int      line = 0,
                                    [CallerMemberName]      string? member = null)
                                {
                                    var p = a.NewPipeline(asserterExpr: aExpr, methodName: "That", valueExpr: vExpr, file: file, line: line, member: member);
                                    return new {{assertionsClass}}(value, p);
                                }
                            }


                        """);
                }
                else
                {
                    sb.Append($$"""
                            public static partial class AsserterExtensions
                            {
                                public static global::Catchy.ValueAssertions<{{fullTarget}}> That(
                                    this global::Catchy.Asserter a, {{fullTarget}} value,
                                    [CallerArgumentExpression(nameof(a))]     string? aExpr = null,
                                    [CallerArgumentExpression(nameof(value))] string? vExpr = null,
                                    [CallerFilePath]      string? file = null,
                                    [CallerLineNumber] int      line = 0,
                                    [CallerMemberName]      string? member = null)
                                {
                                    var p = a.NewPipeline(asserterExpr: aExpr, methodName: "That", valueExpr: vExpr, file: file, line: line, member: member);
                                    return new global::Catchy.ValueAssertions<{{fullTarget}}>(p, value);
                                }
                            }


                        """);
                }

                if (model.Methods.Length > 0)
                {
                    var extensionClassName = target.Mode == GeneratedMode.EntryPoint
                        ? $"{assertionsClass}Extensions"
                        : $"{model.ContainerClassName}_{target.TargetTypeName}ValueAssertionsExtensions";

                    sb.AppendLine($"    public static class {extensionClassName}");
                    sb.AppendLine("    {");
                    foreach (var method in model.Methods)
                        EmitAssertionMethod(sb, method, model.ContainerClassName, fullTarget);
                    sb.AppendLine("    }");
                }

                sb.Append("""
                    }

                    """);

                var hintTarget = SanitizeName(fullTarget.Replace("global::", string.Empty));
                var hint = $"AssertFor_{SanitizeName(model.Namespace)}_{SanitizeName(model.ContainerClassName)}_{hintTarget}.g.cs";
                spc.AddSource(hint, SourceText.From(sb.ToString(), Encoding.UTF8));
            }
        }

        private static ImmutableArray<CrossTypeRuleModel> DiscoverCrossTypeRules(Compilation compilation)
        {
            var builder = ImmutableArray.CreateBuilder<CrossTypeRuleModel>();

            foreach (var assembly in EnumerateAssembliesForExternalRules(compilation))
            {
                foreach (var type in EnumerateAllTypesForExternalRules(assembly.GlobalNamespace))
                {
                    if (type.TypeKind != TypeKind.Class || !type.IsStatic)
                    {
                        continue;
                    }

                    var rules = BuildCrossTypeRulesForContainer(type);
                    if (rules.Length == 0)
                    {
                        continue;
                    }

                    builder.AddRange(rules);
                }
            }

            return [.. builder
                .OrderBy(r => r.Order)
                .ThenBy(r => r.SourceTypeFullName, StringComparer.Ordinal)
                .ThenBy(r => r.TargetTypeFullName, StringComparer.Ordinal)
                .ThenBy(r => r.ContainerClassName, StringComparer.Ordinal)];
        }

        private static ImmutableArray<CrossTypeRuleModel> BuildCrossTypeRulesForContainer(INamedTypeSymbol containerType)
        {
            var rules = ImmutableArray.CreateBuilder<CrossTypeRuleModel>();
            var ruleAttrs = containerType.GetAttributes()
                .Where(a => a.AttributeClass?.ToDisplayString() == "Catchy.CrossTypeRuleAttribute")
                .ToArray();

            if (ruleAttrs.Length == 0)
            {
                return [];
            }

            var mapAttrs = containerType.GetAttributes()
                .Where(a => a.AttributeClass?.ToDisplayString() == "Catchy.CrossTypeMemberMapAttribute")
                .ToArray();

            foreach (var ruleAttr in ruleAttrs)
            {
                if (ruleAttr.ConstructorArguments.Length < 2
                    || ruleAttr.ConstructorArguments[0].Value is not ITypeSymbol sourceType
                    || ruleAttr.ConstructorArguments[1].Value is not ITypeSymbol targetType)
                {
                    continue;
                }

                bool autoMapFields = false;
                bool ignoreExtraFields = true;
                bool registerInGlobalRegistry = true;
                int order = 0;
                string stringComparisonExpression = DefaultStringComparisonExpression;

                foreach (var named in ruleAttr.NamedArguments)
                {
                    switch (named.Key)
                    {
                        case "AutoMapFields" when named.Value.Value is bool auto:
                            autoMapFields = auto;
                            break;
                        case "IgnoreExtraFields" when named.Value.Value is bool ignore:
                            ignoreExtraFields = ignore;
                            break;
                        case "RegisterInGlobalRegistry" when named.Value.Value is bool register:
                            registerInGlobalRegistry = register;
                            break;
                        case "StringComparison":
                            stringComparisonExpression = ParseStringComparisonExpression(named.Value, stringComparisonExpression);
                            break;
                        case "Order" when named.Value.Value is int ord:
                            order = ord;
                            break;
                    }
                }

                var memberMaps = ImmutableArray.CreateBuilder<CrossTypeMemberMapModel>();
                foreach (var mapAttr in mapAttrs)
                {
                    if (mapAttr.ConstructorArguments.Length < 2)
                    {
                        continue;
                    }

                    var sourceMemberName = mapAttr.ConstructorArguments[0].Value?.ToString();
                    var targetMemberName = mapAttr.ConstructorArguments[1].Value?.ToString();
                    if (string.IsNullOrWhiteSpace(sourceMemberName) || string.IsNullOrWhiteSpace(targetMemberName))
                    {
                        continue;
                    }

                    var nonNullSourceMemberName = sourceMemberName!;
                    var nonNullTargetMemberName = targetMemberName!;

                    bool useStringComparison = false;
                    string mapStringComparisonExpression = stringComparisonExpression;
                    string? messageFormat = null;
                    int mapRuleOrder = 0;
                    int mapOrder = 0;

                    foreach (var named in mapAttr.NamedArguments)
                    {
                        switch (named.Key)
                        {
                            case "UseStringComparison" when named.Value.Value is bool use:
                                useStringComparison = use;
                                break;
                            case "StringComparison":
                                mapStringComparisonExpression = ParseStringComparisonExpression(named.Value, stringComparisonExpression);
                                break;
                            case "MessageFormat" when named.Value.Value is string m:
                                messageFormat = m;
                                break;
                            case "RuleOrder" when named.Value.Value is int ro:
                                mapRuleOrder = ro;
                                break;
                            case "Order" when named.Value.Value is int mo:
                                mapOrder = mo;
                                break;
                        }
                    }

                    if (mapRuleOrder != order)
                    {
                        continue;
                    }

                    memberMaps.Add(new CrossTypeMemberMapModel(
                        nonNullSourceMemberName,
                        nonNullTargetMemberName,
                        useStringComparison,
                        mapStringComparisonExpression,
                        messageFormat,
                        mapOrder));
                }

                var ns = containerType.ContainingNamespace?.IsGlobalNamespace == false
                    ? containerType.ContainingNamespace.ToDisplayString()
                    : "";

                rules.Add(new CrossTypeRuleModel(
                    ns,
                    containerType.Name,
                    EnsureGlobalQualification(sourceType.ToDisplayString()),
                    EnsureGlobalQualification(targetType.ToDisplayString()),
                    autoMapFields,
                    ignoreExtraFields,
                    registerInGlobalRegistry,
                    stringComparisonExpression,
                    order,
                    [.. memberMaps.OrderBy(m => m.Order)]));
            }

            return rules.ToImmutableArray();
        }

        private static IEnumerable<IAssemblySymbol> EnumerateAssembliesForExternalRules(Compilation compilation)
        {
            yield return compilation.Assembly;

            foreach (var assembly in compilation.SourceModule.ReferencedAssemblySymbols
                         .OrderBy(a => a.Name, StringComparer.Ordinal))
            {
                yield return assembly;
            }
        }

        private static IEnumerable<INamedTypeSymbol> EnumerateAllTypesForExternalRules(INamespaceSymbol @namespace)
        {
            foreach (var member in @namespace.GetTypeMembers())
            {
                foreach (var type in EnumerateTypeAndNestedForExternalRules(member))
                {
                    yield return type;
                }
            }

            foreach (var childNamespace in @namespace.GetNamespaceMembers())
            {
                foreach (var type in EnumerateAllTypesForExternalRules(childNamespace))
                {
                    yield return type;
                }
            }
        }

        private static IEnumerable<INamedTypeSymbol> EnumerateTypeAndNestedForExternalRules(INamedTypeSymbol type)
        {
            yield return type;

            foreach (var nested in type.GetTypeMembers())
            {
                foreach (var child in EnumerateTypeAndNestedForExternalRules(nested))
                {
                    yield return child;
                }
            }
        }

        private static void EmitCrossTypeRules(
            SourceProductionContext spc,
            ImmutableArray<CrossTypeRuleModel> models,
            ImmutableArray<RulePairModel> inlineRulePairs)
        {
            var inlinePairs = new HashSet<(string SourceTypeFullName, string TargetTypeFullName)>(
                inlineRulePairs.Select(p => (p.SourceTypeFullName, p.TargetTypeFullName)));

            var applicable = models
                .Where(m => m.RegisterInGlobalRegistry)
                .Where(m => m.MemberMaps.Length > 0)
                .Where(m => !inlinePairs.Contains((m.SourceTypeFullName, m.TargetTypeFullName)))
                .ToArray();

            if (applicable.Length == 0)
            {
                return;
            }

            var sb = new StringBuilder();
            sb.Append("""
                // <auto-generated/>
                #nullable enable
                using System.Collections.Generic;
                using System.Runtime.CompilerServices;

                namespace Catchy.Generated
                {
                    internal static class CrossTypeRulesRegistrar
                    {
                        private sealed class StringComparisonObjectComparer : IEqualityComparer<object?>
                        {
                            private readonly global::System.StringComparison _comparison;
                            public StringComparisonObjectComparer(global::System.StringComparison comparison) => _comparison = comparison;
                            public new bool Equals(object? x, object? y)
                            {
                                if (x is string sx && y is string sy)
                                {
                                    return string.Equals(sx, sy, _comparison);
                                }
                                return object.Equals(x, y);
                            }
                            public int GetHashCode(object? obj) => obj?.GetHashCode() ?? 0;
                        }

                        [ModuleInitializer]
                        internal static void Register()
                        {

                """);

            foreach (var rule in applicable)
            {
                sb.AppendLine($"            if (!global::Catchy.Sdk.DeepEqualRuleRegistry.HasRule<{rule.SourceTypeFullName}, {rule.TargetTypeFullName}>())");
                sb.AppendLine("            {");
                sb.AppendLine($"                var ruleBuilder = global::Catchy.DeepEqualRule.For<{rule.SourceTypeFullName}, {rule.TargetTypeFullName}>(disableReflection: true);");

                foreach (var map in rule.MemberMaps)
                {
                    var safeName = $"{rule.ContainerClassName}:{map.SourceMemberName}->{map.TargetMemberName}".Replace("\"", "\\\"");
                    if (map.UseStringComparison)
                    {
                        sb.AppendLine($"                ruleBuilder = ruleBuilder.Match<object?>(s => (object?)s.{map.SourceMemberName}, t => (object?)t.{map.TargetMemberName}, comparer: new StringComparisonObjectComparer({map.StringComparisonExpression}), name: \"{safeName}\");");
                    }
                    else
                    {
                        sb.AppendLine($"                ruleBuilder = ruleBuilder.Match<object?>(s => (object?)s.{map.SourceMemberName}, t => (object?)t.{map.TargetMemberName}, comparer: null, name: \"{safeName}\");");
                    }
                }

                sb.AppendLine("                ruleBuilder.Register();");
                sb.AppendLine("            }");
            }

            sb.Append("""
                        }
                    }
                }

                """);

            spc.AddSource("CrossTypeRules_Registrar.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        private static void EmitAssertionMethod(StringBuilder sb, AssertionMethodModel method,
            string containerClass, string fullTarget)
        {
            var extraParamList = method.Parameters.Length > 0
                ? ", " + string.Join(", ", method.Parameters.Select(p => $"{p.Type} {p.Name}"))
                : "";

            var extraArgs = method.Parameters.Length > 0
                ? ", " + string.Join(", ", method.Parameters.Select(p => p.Name))
                : "";

            var receiverType = $"global::Catchy.ValueAssertions<{fullTarget}>";

            if (method.IsAsync)
            {
                sb.Append($$"""
                            [DebuggerHidden, StackTraceHidden, AssertionMethod]
                            public static {{receiverType}} {{method.MethodName}}(this {{receiverType}} a{{extraParamList}})
                            {
                                a.Link("{{method.MethodName}}");
                                a.Op(CheckOperation.Async(async () =>
                                {
                                    var v = a.GetValue();
                                    return v is not null && await {{containerClass}}.{{method.MethodName}}(v{{extraArgs}}).ConfigureAwait(false);
                                },
                                    () => $"Expected {a.GetValue()} {{method.ExpectationMessage}}",
                                    a.IsSkipped()));
                                return a;
                            }


                    """);
            }
            else
            {
                sb.Append($$"""
                            [DebuggerHidden, StackTraceHidden, AssertionMethod]
                            public static {{receiverType}} {{method.MethodName}}(this {{receiverType}} a{{extraParamList}})
                            {
                                a.Link("{{method.MethodName}}");
                                a.Op(CheckOperation.Sync(
                                    () =>
                                    {
                                        var v = a.GetValue();
                                        return v is not null && {{containerClass}}.{{method.MethodName}}(v{{extraArgs}});
                                    },
                                    () => $"Expected {a.GetValue()} {{method.ExpectationMessage}}",
                                    a.IsSkipped()));
                                return a;
                            }


                    """);
            }
        }

        private sealed record ArityMethodModel(
            string Namespace,
            string ClassName,
            string MethodName,
            string ReturnType,
            string SelfType,
            string ElementType,
            string TargetParamName,
            string? TargetCaeParamName,
            ImmutableArray<ExtraParam> ExtraParams,
            ImmutableArray<string> MethodTypeParameters,
            ImmutableArray<string> MethodConstraints,
            int From,
            int To);

        private sealed record ExtraParam(string Type, string Name, string? Default, string? CaeTarget);

        private static ArityMethodModel? GetArityModel(
            GeneratorAttributeSyntaxContext ctx, System.Threading.CancellationToken ct)
        {
            if (ctx.TargetSymbol is not IMethodSymbol method) 
                return null;
            ct.ThrowIfCancellationRequested();

            var attr = ctx.Attributes.FirstOrDefault();
            if (attr is null) return null;

            string target = "values";
            int from = 2, to = 5;

            if (attr.ConstructorArguments.Length > 0 && attr.ConstructorArguments[0].Value is string targetArg)
                target = targetArg;
            if (attr.ConstructorArguments.Length > 1 && attr.ConstructorArguments[1].Value is int fromArg)
                from = fromArg;
            if (attr.ConstructorArguments.Length > 2 && attr.ConstructorArguments[2].Value is int toArg)
                to = toArg;

            foreach (var named in attr.NamedArguments)
            {
                switch (named.Key)
                {
                    case "Target" when named.Value.Value is string s: target = s; break;
                    case "From" when named.Value.Value is int i: from = i; break;
                    case "To" when named.Value.Value is int j: to = j; break;
                }
            }

            var allParams = method.Parameters;
            if (allParams.Length == 0) 
                return null;

            // For extension methods, first param is 'this'
            var targetParam = allParams.FirstOrDefault(p => p.Name == target);
            if (targetParam is null) 
            {
                // Target parameter not found
                return null;
            }

            var elemType = ExtractEnumerableElementType(targetParam.Type);
            if (elemType is null) 
            {
                // Element type not extracted - not an IEnumerable<T>
                return null;
            }

            var targetCaePName = allParams.FirstOrDefault(p => IsCallerExpressionFor(p, target))?.Name;

            var extras = allParams
                .Where(p => p.Name != allParams[0].Name
                         && p.Name != target
                         && p.Name != targetCaePName)
                .Select(p => new ExtraParam(
                    p.Type.ToDisplayString(),
                    p.Name,
                    p.HasExplicitDefaultValue ? FormatDefault(p.ExplicitDefaultValue) : null,
                    GetCallerExpressionTarget(p)))
                .ToImmutableArray();

            var containingType = method.ContainingType;
            if (containingType is null) return null; // No containing type

            var ns = containingType.ContainingNamespace?.IsGlobalNamespace == false
                ? containingType.ContainingNamespace.ToDisplayString()
                : "Catchy";

            var methodTypeParameters = method.TypeParameters.Select(tp => tp.Name).ToImmutableArray();
            var methodConstraints = method.TypeParameters
                .Select(BuildTypeParameterConstraintClause)
                .Where(c => !string.IsNullOrWhiteSpace(c))
                .Select(c => c!)
                .ToImmutableArray();

            return new ArityMethodModel(
                ns,
                containingType.Name,
                method.Name,
                method.ReturnType.ToDisplayString(),
                allParams[0].Type.ToDisplayString(),
                elemType,
                target,
                targetCaePName,
                extras,
                methodTypeParameters,
                methodConstraints,
                from, to);
        }

        private static void EmitArityOverloads(
            SourceProductionContext spc, ImmutableArray<ArityMethodModel?> models)
        {
            var valid = models.Where(m => m is not null).Select(m => m!).ToList();

            if (valid.Count == 0) return;

            var sb = new StringBuilder();
            sb.Append("""
                // <auto-generated/>
                #nullable enable
                using System;
                using System.Collections.Generic;
                using System.Diagnostics;
                using System.Runtime.CompilerServices;
                using Catchy.Sdk;


                """);

            foreach (var grp in valid.GroupBy(m => (m.Namespace, m.ClassName)))
            {
                sb.AppendLine($"namespace {grp.Key.Namespace}");
                sb.AppendLine("{");
                sb.AppendLine($"    public static partial class {grp.Key.ClassName}");
                sb.AppendLine("    {");
                foreach (var model in grp) EmitSingleArityMethod(sb, model);
                sb.AppendLine("    }");
                sb.AppendLine("}");
                sb.AppendLine();
            }

            spc.AddSource("ArityOverloads.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        private static void EmitSingleArityMethod(StringBuilder sb, ArityMethodModel model)
        {
            var nonCae = model.ExtraParams.Where(p => p.CaeTarget is null).ToList();
            var caeMap = model.ExtraParams.Where(p => p.CaeTarget is not null)
                .ToDictionary(p => p.CaeTarget!, p => p);

            var c = model.TargetParamName[0];

            for (int n = model.From; n <= model.To; n++)
            {
                EmitSingleArityOverload(sb, model, nonCae, caeMap, c, n);
            }
        }

        private static void EmitSingleArityOverload(StringBuilder sb, ArityMethodModel model, 
            List<ExtraParam> nonCae, Dictionary<string, ExtraParam> caeMap, char c, int n)
        {
            var vPs = string.Join(", ", Enumerable.Range(1, n).Select(i => $"{model.ElementType} {c}{i}"));
            var otherStr = BuildOtherParamString(nonCae);
            var sep = BuildSeparatorString(model.ElementType, nonCae);
            var caeParams = string.Join(", ",
                Enumerable.Range(1, n).Select(i => $"[CallerArgumentExpression(nameof({c}{i}))] string? _e{i} = null"));
            var otherCaePart = BuildOtherCaeString(nonCae, caeMap);
            var otherFwd = nonCae.Count > 0
                ? ", " + string.Join(", ", nonCae.Select(p => $"{p.Name}: {p.Name}"))
                : "";
            var vals = string.Join(", ", Enumerable.Range(1, n).Select(i => $"{c}{i}"));
            var targetCaeArg = BuildTargetCaeArg(model, nonCae, n);

            var genericSuffix = model.MethodTypeParameters.Length > 0
                ? $"<{string.Join(", ", model.MethodTypeParameters)}>": string.Empty;
            AppendGeneratedSummary(sb, 2, $"Convenience overload for {model.MethodName} with {n} values.");
            sb.AppendLine("        [DebuggerHidden, StackTraceHidden, AssertionMethod]");
            sb.AppendLine($"        public static {model.ReturnType} {model.MethodName}{genericSuffix}(this {model.SelfType} a, {vPs}{sep}{otherStr}, {caeParams}{otherCaePart})");
            foreach (var constraint in model.MethodConstraints)
                sb.AppendLine($"            {constraint}");
            sb.AppendLine("        {");
            sb.AppendLine($"            return {model.MethodName}(a, new {model.ElementType}[] {{ {vals} }}{otherFwd}{targetCaeArg});");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        private static string BuildOtherParamString(List<ExtraParam> nonCae)
            => nonCae.Count > 0
                ? ", " + string.Join(", ", nonCae.Select(p => { var s = $"{p.Type} {p.Name}"; return p.Default is not null ? s + " = " + p.Default : s; }))
                : "";

        private static void AppendGeneratedSummary(StringBuilder sb, int indentLevel, string summary)
        {
            var indent = new string(' ', indentLevel * 4);
            sb.AppendLine($"{indent}/// <summary>");
            sb.AppendLine($"{indent}/// {EscapeXmlText(summary)}");
            sb.AppendLine($"{indent}/// </summary>");
        }

        private static void AppendIndentedDocumentationComment(StringBuilder sb, string xml, int indentLevel, string fallbackSummary)
        {
            if (string.IsNullOrWhiteSpace(xml))
            {
                AppendGeneratedSummary(sb, indentLevel, fallbackSummary);
                return;
            }

            var indent = new string(' ', indentLevel * 4);
            var lines = xml.Replace("\r\n", "\n").Replace('\r', '\n').Split('\n');
            var wroteAny = false;
            foreach (var line in lines)
            {
                var trimmed = line.Trim();
                if (trimmed.Length == 0)
                {
                    continue;
                }

                sb.AppendLine($"{indent}/// {trimmed}");
                wroteAny = true;
            }

            if (!wroteAny)
            {
                AppendGeneratedSummary(sb, indentLevel, fallbackSummary);
            }
        }

        private static string EscapeXmlText(string text)
            => text
                .Replace("&", "&amp;")
                .Replace("<", "&lt;")
                .Replace(">", "&gt;");

        private static string BuildSeparatorString(string elementType, List<ExtraParam> nonCae)
        {
            var elem = elementType.Trim().TrimEnd('?');
            var elemIsString = elem == "string";
            var elemIsGenericParam = IsGenericTypeParamToken(elem);
            if (!elemIsString && !elemIsGenericParam)
                return "";

            if (nonCae.Count == 0)
                return ", global::__._ _ = default";

            var first = nonCae[0].Type.Trim().TrimEnd('?');
            if (elemIsString)
                return first == "string" ? ", global::__._ _ = default" : "";

            return (first == "string" || IsGenericTypeParamToken(first)) ? ", global::__._ _ = default" : "";
        }

        private static bool IsGenericTypeParamToken(string t)
            => !string.IsNullOrWhiteSpace(t) && t.All(ch => char.IsLetterOrDigit(ch) || ch == '_') && char.IsUpper(t[0]);

        private static string BuildOtherCaeString(List<ExtraParam> nonCae, Dictionary<string, ExtraParam> caeMap)
        {
            var otherCaeStr = string.Join(", ",
                nonCae.Where(p => caeMap.ContainsKey(p.Name))
                      .Select(p => $"[CallerArgumentExpression(nameof({p.Name}))] string? {caeMap[p.Name].Name} = null"));
            return otherCaeStr.Length > 0 ? ", " + otherCaeStr : "";
        }

        private static string BuildTargetCaeArg(ArityMethodModel model, List<ExtraParam> nonCae, int n)
        {
            if (model.TargetCaeParamName is null) return "";
            if (nonCae.Any(p => p.Name == model.TargetCaeParamName)) return "";
            var exprFmt = string.Join(", ", Enumerable.Range(1, n).Select(i => $"{{_e{i}}}"));
            return $", {model.TargetCaeParamName}: $\"{exprFmt}\"";
        }

        private static string? ExtractEnumerableElementType(ITypeSymbol type)
        {
            // Handle nullable types - unwrap if needed
            // For nullable reference types like "IEnumerable<T>?", we need to check the original type
            ITypeSymbol baseType = type;

            // If it's a nullable reference type, it will still be INamedTypeSymbol but with NullableAnnotation set
            // We don't need to unwrap - Roslyn gives us IEnumerable<T> regardless

            if (baseType is INamedTypeSymbol named)
            {
                // Direct match: IEnumerable<T> where T can be a type parameter or concrete type
                if (named.Name == "IEnumerable" && named.TypeArguments.Length == 1)
                {
                    // Check namespace - it should be System.Collections.Generic
                    var ns = named.ContainingNamespace?.ToDisplayString();
                    if (string.IsNullOrEmpty(ns) || ns == "System.Collections.Generic")
                    {
                        // Return element type as string - for "IEnumerable<T>" this returns "T"
                        var elemType = named.TypeArguments[0];
                        return elemType.ToDisplayString();
                    }
                }

                // Check if this type implements IEnumerable<T>
                foreach (var iface in named.AllInterfaces)
                {
                    if (iface.Name == "IEnumerable" && iface.TypeArguments.Length == 1)
                    {
                        var ns = iface.ContainingNamespace?.ToDisplayString();
                        if (string.IsNullOrEmpty(ns) || ns == "System.Collections.Generic")
                        {
                            return iface.TypeArguments[0].ToDisplayString();
                        }
                    }
                }
            }

            return null;
        }

        private static string? BuildTypeParameterConstraintClause(ITypeParameterSymbol tp)
        {
            var parts = new List<string>();
            if (tp.HasReferenceTypeConstraint) parts.Add("class");
            if (tp.HasValueTypeConstraint) parts.Add("struct");
            if (tp.HasUnmanagedTypeConstraint) parts.Add("unmanaged");
            foreach (var ct in tp.ConstraintTypes)
                parts.Add(ct.ToDisplayString());
            if (tp.HasNotNullConstraint) parts.Add("notnull");
            if (tp.HasConstructorConstraint) parts.Add("new()");
            if (parts.Count == 0) return null;
            return $"where {tp.Name} : {string.Join(", ", parts)}";
        }

        private static bool IsCallerExpressionFor(IParameterSymbol p, string targetName)
        {
            foreach (var attr in p.GetAttributes())
            {
                if (attr.AttributeClass?.Name.Contains("CallerArgumentExpression") != true) continue;
                if (attr.ConstructorArguments.FirstOrDefault().Value is string s
                    && s == targetName) return true;
            }
            return false;
        }

        private static string? GetCallerExpressionTarget(IParameterSymbol p)
        {
            foreach (var attr in p.GetAttributes())
            {
                if (attr.AttributeClass?.Name.Contains("CallerArgumentExpression") != true) continue;
                if (attr.ConstructorArguments.FirstOrDefault().Value is string s) return s;
            }
            return null;
        }

        private sealed record MethodTemplateMetadataModel(
            MethodTemplateDiscoveryResult Discovery);

        private static MethodTemplateMetadataModel BuildMethodTemplateMetadata(Compilation compilation)
        {
            var discovery = new MethodTemplateDiscovery().Discover(compilation);
            return new MethodTemplateMetadataModel(discovery);
        }

                private static void EmitMethodTemplates(SourceProductionContext spc, MethodTemplateMetadataModel metadata)
        {
            foreach (var diagnostic in metadata.Discovery.Diagnostics)
            {
                var descriptor = new DiagnosticDescriptor(
                    id: diagnostic.Code,
                    title: "Catchy SourceGenerator MethodTemplate",
                    messageFormat: diagnostic.Message,
                    category: "Catchy.SourceGenerator",
                    defaultSeverity: diagnostic.Severity,
                    isEnabledByDefault: true);

                spc.ReportDiagnostic(Diagnostic.Create(descriptor, Location.None));
            }

            foreach (var group in metadata.Discovery.Methods.GroupBy(m => m.ContainingTypeName, StringComparer.Ordinal))
            {
                EmitMethodTemplatePartialType(spc, group.Key, [.. group]);
            }
        }

        private static void EmitMethodTemplatePartialType(
            SourceProductionContext spc,
            string containingTypeName,
            ImmutableArray<MethodTemplateDiscoveredMethod> methods)
        {
            if (methods.Length == 0)
            {
                return;
            }

            var templateMethods = methods
                .SelectMany(method => method.TemplateTargetTypeNames.Select(targetType => (method, targetType)))
                .OrderBy(x => x.method.MethodName, StringComparer.Ordinal)
                .ThenBy(x => x.targetType, StringComparer.Ordinal)
                .ToArray();

            if (templateMethods.Length == 0)
            {
                return;
            }

            var first = methods[0];
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System.Diagnostics;");
            sb.AppendLine("using System.Runtime.CompilerServices;");
            sb.AppendLine("using Catchy;");
            sb.AppendLine("using Catchy.Sdk;");
            sb.AppendLine();

            if (!string.IsNullOrWhiteSpace(first.ContainingNamespace))
            {
                sb.AppendLine($"namespace {first.ContainingNamespace}");
                sb.AppendLine("{");
            }

            var typeIndentLevel = string.IsNullOrWhiteSpace(first.ContainingNamespace) ? 0 : 1;
            var typeIndent = new string(' ', typeIndentLevel * 4);
            var containingTypeShortName = GetContainingTypeShortName(containingTypeName);
            sb.AppendLine($"{typeIndent}{first.ContainingTypeModifiers} class {containingTypeShortName}");
            sb.AppendLine($"{typeIndent}{{");

            var emittedSignatures = new HashSet<string>(StringComparer.Ordinal);
            foreach (var (method, targetType) in templateMethods)
            {
                EmitMethodTemplateMethod(sb, method, targetType, emittedSignatures, typeIndentLevel + 1);
            }

            sb.AppendLine($"{typeIndent}}}");
            if (!string.IsNullOrWhiteSpace(first.ContainingNamespace))
            {
                sb.AppendLine("}");
            }

            spc.AddSource($"MethodTemplate_{SanitizeName(containingTypeName)}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        private static void EmitMethodTemplateMethod(
            StringBuilder sb,
            MethodTemplateDiscoveredMethod method,
            string concreteTypeName,
            HashSet<string> emittedSignatures,
            int indentLevel)
        {
            // Skip if target equals the template type: the original method already covers it.
            if (string.Equals(concreteTypeName, method.TemplateValueTypeName, StringComparison.Ordinal))
            {
                return;
            }

            var substitutions = new Dictionary<string, string>(StringComparer.Ordinal)
            {
                [method.TemplateValueTypeName] = concreteTypeName
            };

            var returnTypeName = TemplateDiscoveryHelpers.SubstituteTypeParams(method.ReturnTypeName, substitutions);
            var receiverTypeName = TemplateDiscoveryHelpers.SubstituteTypeParams(method.ReceiverTypeName, substitutions);
            var additionalParametersSignature = TemplateDiscoveryHelpers.SubstituteTypeParams(method.AdditionalParametersSignature, substitutions);
            var methodBodySource = TemplateDiscoveryHelpers.SubstituteTypeParams(method.MethodBodySource, substitutions);
            var documentationCommentXml = TemplateDiscoveryHelpers.SubstituteTypeParams(method.DocumentationCommentXml, substitutions);
            var methodTypeParametersDeclaration = TemplateDiscoveryHelpers.RemoveTypeParameterFromDeclaration(method.WrapperMethodTypeParametersDeclaration, method.TemplateValueTypeName);
            var methodTypeConstraints = TemplateDiscoveryHelpers.RemoveTypeParameterConstraintClause(method.WrapperMethodTypeConstraints, method.TemplateValueTypeName);

            var targetTypeQualified = EnsureGlobalQualification(receiverTypeName);
            var methodParameters = string.IsNullOrWhiteSpace(additionalParametersSignature)
                ? $"this {targetTypeQualified} {method.ReceiverParameterName}"
                : $"this {targetTypeQualified} {method.ReceiverParameterName}, {additionalParametersSignature}";
            var signatureGenericArity = ParseTypeParameterNames(methodTypeParametersDeclaration).Length;
            var emittedSignature = BuildWrapperSignatureKey(method.MethodName, signatureGenericArity, targetTypeQualified, additionalParametersSignature);
            if (!emittedSignatures.Add(emittedSignature))
            {
                return;
            }

            AppendIndentedDocumentationComment(sb, documentationCommentXml, indentLevel,
                $"Applies {method.MethodName} to this assertion chain.");
            var indent = new string(' ', indentLevel * 4);
            // Forward any [GenerateArityOverloads] from the template method onto every concrete overload
            // so the arity generator fires for all generated copies, not just the original template.
            foreach (var arity in method.ArityForwards)
            {
                sb.AppendLine($"{indent}[global::Catchy.Sdk.GenerateArityOverloads(\"{arity.Target}\", from: {arity.From}, to: {arity.To})]");
            }
            sb.AppendLine($"{indent}[DebuggerHidden]");
            sb.AppendLine($"{indent}{method.MethodModifiers} {EnsureGlobalQualification(returnTypeName)} {method.MethodName}{methodTypeParametersDeclaration}({methodParameters})");
            if (!string.IsNullOrWhiteSpace(methodTypeConstraints))
            {
                sb.AppendLine($"{indent}    {methodTypeConstraints}");
            }
            sb.AppendLine($"{indent}{{");
            AppendMethodBody(sb, methodBodySource, indentLevel + 1, method.ReturnsVoid);
            sb.AppendLine($"{indent}}}");
            sb.AppendLine();
        }

                private static ImmutableArray<string> ParseTypeParameterNames(string typeParamsDecl)
        {
            if (string.IsNullOrWhiteSpace(typeParamsDecl))
                return [];
            // typeParamsDecl is like "<T>" or "<T, U>"
            var inner = typeParamsDecl.Trim('<', '>').Trim();
            if (string.IsNullOrWhiteSpace(inner))
                return [];
            return [.. inner.Split(',')
                .Select(s => s.Trim())
                .Where(s => !string.IsNullOrWhiteSpace(s))];
        }

        private static void AppendMethodBody(StringBuilder sb, string methodBodySource, int indentLevel, bool returnsVoid)
        {
            var indent = new string(' ', indentLevel * 4);
            var body = string.IsNullOrWhiteSpace(methodBodySource)
                ? (returnsVoid ? "{ }" : "{ return self; }")
                : methodBodySource.Trim();

            if (body.StartsWith("=>", StringComparison.Ordinal))
            {
                var expression = body.Substring(2).Trim().TrimEnd(';');
                sb.AppendLine(returnsVoid
                    ? $"{indent}{expression};"
                    : $"{indent}return {expression};");
                return;
            }

            if (!body.StartsWith("{", StringComparison.Ordinal) || !body.EndsWith("}", StringComparison.Ordinal))
            {
                sb.AppendLine($"{indent}{body}");
                return;
            }

            var inner = body.Substring(1, body.Length - 2);
            var lines = inner.Replace("\r\n", "\n").Split('\n');
            foreach (var line in lines)
            {
                if (line.Length == 0)
                {
                    sb.AppendLine();
                    continue;
                }

                sb.Append(indent);
                sb.AppendLine(line);
            }
        }

        private static string BuildWrapperSignatureKey(
            string methodName,
            int genericArity,
            string targetTypeQualified,
            string additionalParametersSignature)
        {
            var normalizedTarget = NormalizeTypeForSignature(targetTypeQualified);
            var normalizedParams = string.IsNullOrWhiteSpace(additionalParametersSignature)
                ? string.Empty
                : string.Join("|", SplitTopLevelCommaSeparated(additionalParametersSignature)
                    .Select(NormalizeParameterDeclarationForSignature));

            return $"{methodName}`{genericArity}|this:{normalizedTarget}|{normalizedParams}";
        }

        private static string NormalizeParameterDeclarationForSignature(string declaration)
        {
            var trimmed = declaration.Trim();
            var modifier = string.Empty;

            if (trimmed.StartsWith("params ", StringComparison.Ordinal))
            {
                modifier += "params ";
                trimmed = trimmed.Substring("params ".Length);
            }

            if (trimmed.StartsWith("ref ", StringComparison.Ordinal))
            {
                modifier += "ref ";
                trimmed = trimmed.Substring("ref ".Length);
            }
            else if (trimmed.StartsWith("out ", StringComparison.Ordinal))
            {
                modifier += "out ";
                trimmed = trimmed.Substring("out ".Length);
            }
            else if (trimmed.StartsWith("in ", StringComparison.Ordinal))
            {
                modifier += "in ";
                trimmed = trimmed.Substring("in ".Length);
            }

            var spaceIdx = trimmed.LastIndexOf(' ');
            var typePart = spaceIdx > 0 ? trimmed.Substring(0, spaceIdx) : trimmed;
            return $"{modifier}{NormalizeTypeForSignature(typePart)}";
        }

        private static string NormalizeTypeForSignature(string typeName)
            => typeName.Replace("?", string.Empty).Trim();

        private static IEnumerable<string> SplitTopLevelCommaSeparated(string value)
        {
            if (string.IsNullOrWhiteSpace(value))
                yield break;

            var depthAngle = 0;
            var depthParen = 0;
            var start = 0;

            for (var i = 0; i < value.Length; i++)
            {
                var ch = value[i];
                switch (ch)
                {
                    case '<':
                        depthAngle++;
                        break;
                    case '>':
                        if (depthAngle > 0) depthAngle--;
                        break;
                    case '(':
                        depthParen++;
                        break;
                    case ')':
                        if (depthParen > 0) depthParen--;
                        break;
                    case ',':
                        if (depthAngle == 0 && depthParen == 0)
                        {
                            yield return value.Substring(start, i - start).Trim();
                            start = i + 1;
                        }
                        break;
                }
            }

            if (start < value.Length)
            {
                yield return value.Substring(start).Trim();
            }
        }

        private static string FormatDefault(object? value) => value switch
        {
            null => "default",
            string s => $"\"{s}\"",
            bool b => b ? "true" : "false",
            _ => value.ToString() ?? "default"
        };

        private static string SanitizeName(string name)
            => name
                .Replace(".", "_")
                .Replace("<", "_")
                .Replace(">", "_")
                .Replace("?", "Nullable")
                .Replace(",", "_")
                .Replace(" ", "");

        private static string GetContainingTypeShortName(string fullName)
        {
            var genericStart = fullName.IndexOf('<');
            var nsSearchRange = genericStart >= 0
                ? fullName.Substring(0, genericStart)
                : fullName;
            var lastDot = nsSearchRange.LastIndexOf('.');
            return lastDot >= 0 ? fullName.Substring(lastDot + 1) : fullName;
        }

        private static string GetTypeName(string fullName)
        {
            // Extract the last part of a fully qualified name
            var parts = fullName.Split('.');
            var typeName = parts.Length > 0 ? parts[parts.Length - 1] : fullName;
            // Remove generic parameters and nullability
            return typeName.Split('<')[0].TrimEnd('?');
        }

        // ── AssertEntry discovery ────────────────────────────────────────────────

        private static ImmutableArray<AssertEntryModel> DiscoverAssertEntryModels(Compilation compilation)
        {
            var builder = ImmutableArray.CreateBuilder<AssertEntryModel>();
            var attrFqn = AssertEntryAttributeFqn;

            // Class-level: [AssertEntry] on the class itself
            foreach (var assembly in EnumerateAssembliesForExternalRules(compilation))
            {
                foreach (var type in EnumerateAllTypesForExternalRules(assembly.GlobalNamespace))
                {
                    if (type.TypeKind != TypeKind.Class && type.TypeKind != TypeKind.Interface)
                        continue;

                    var attr = type.GetAttributes()
                        .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == attrFqn);
                    if (attr is null)
                        continue;

                    var ns = type.ContainingNamespace.IsGlobalNamespace
                        ? string.Empty
                        : type.ContainingNamespace.ToDisplayString();

                    builder.Add(new AssertEntryModel(
                        Namespace: ns,
                        BaseTypeFullName: type.ToDisplayString(),
                        BaseTypeName: type.Name));
                }
            }

            // Assembly-level: [assembly: AssertEntry(typeof(T))]
            foreach (var assembly in EnumerateAssembliesForExternalRules(compilation))
            {
                var entries = assembly.GetAttributes()
                    .Where(a => a.AttributeClass?.ToDisplayString() == attrFqn)
                    .Where(attr => attr.ConstructorArguments.Length >= 1
                        && attr.ConstructorArguments[0].Value is ITypeSymbol)
                    .Select(attr =>
                    {
                        var targetType = (ITypeSymbol)attr.ConstructorArguments[0].Value!;
                        var ns = targetType.ContainingNamespace is { IsGlobalNamespace: false } ns2
                            ? ns2.ToDisplayString()
                            : string.Empty;

                        return new AssertEntryModel(
                            Namespace: ns,
                            BaseTypeFullName: targetType.ToDisplayString(),
                            BaseTypeName: targetType.Name);
                    });

                builder.AddRange(entries);
            }

            return [.. builder
                .GroupBy(m => m.BaseTypeFullName)
                .Select(g => g.First())];
        }

        private static void EmitAssertEntries(SourceProductionContext spc, ImmutableArray<AssertEntryModel> models)
        {
            if (models.IsEmpty)
                return;

            foreach (var model in models)
            {
                EmitAssertEntryExtensions(spc, model);
            }
        }

        private static void EmitAssertEntryExtensions(SourceProductionContext spc, AssertEntryModel model)
        {
            var baseTypeFq = $"global::{model.BaseTypeFullName}";
            var safeClassName = $"{model.BaseTypeName}AssertEntryExtensions";

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System.Runtime.CompilerServices;");
            sb.AppendLine("using Catchy;");
            sb.AppendLine("using Catchy.Sdk;");
            sb.AppendLine();

            bool hasNs = !string.IsNullOrEmpty(model.Namespace);
            if (hasNs)
            {
                sb.AppendLine($"namespace {model.Namespace}");
                sb.AppendLine("{");
            }

            AppendGeneratedSummary(sb, 1, $"Generated entry-point extensions for assertions on types deriving from {model.BaseTypeName}.");
            sb.AppendLine($"    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
            sb.AppendLine($"    public static class {safeClassName}");
            sb.AppendLine("    {");

            AppendGeneratedSummary(sb, 2,
                $"Starts an assertion chain for a value of type T where T : {model.BaseTypeName}. " +
                "Extension methods visible in IntelliSense are narrowed to those applicable to T.");
            sb.AppendLine("        public static global::Catchy.ValueAssertions<T> That<T>(");
            sb.AppendLine("            this global::Catchy.Asserter a,");
            sb.AppendLine("            T value,");
            sb.AppendLine("            [CallerArgumentExpression(nameof(a))]     string? aExpr   = null,");
            sb.AppendLine("            [CallerArgumentExpression(nameof(value))] string? vExpr   = null,");
            sb.AppendLine("            [CallerFilePath]                          string? file    = null,");
            sb.AppendLine("            [CallerLineNumber]                        int     line    = 0,");
            sb.AppendLine("            [CallerMemberName]                        string? member  = null)");
            sb.AppendLine($"            where T : {baseTypeFq}");
            sb.AppendLine("        {");
            sb.AppendLine("            var pipeline = a.NewPipeline(asserterExpr: aExpr, methodName: \"That\", valueExpr: vExpr, file: file, line: line, member: member);");
            sb.AppendLine("            return new global::Catchy.ValueAssertions<T>(pipeline, value);");
            sb.AppendLine("        }");
            sb.AppendLine("    }");

            if (hasNs)
                sb.AppendLine("}");

            spc.AddSource($"{safeClassName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        // ── AssertVia discovery ──────────────────────────────────────────────────

        private static ImmutableArray<AssertViaModel> DiscoverAssertViaModels(Compilation compilation)
        {
            var builder = ImmutableArray.CreateBuilder<AssertViaModel>();
            var attrFqn = AssertViaAttributeFqn;

            // Class-level: [AssertVia("PropertyName")] on the class itself
            foreach (var assembly in EnumerateAssembliesForExternalRules(compilation))
            {
                foreach (var type in EnumerateAllTypesForExternalRules(assembly.GlobalNamespace))
                {
                    if (type.TypeKind != TypeKind.Class && type.TypeKind != TypeKind.Interface)
                        continue;

                    var viaModels = type.GetAttributes()
                        .Where(a => a.AttributeClass?.ToDisplayString() == attrFqn)
                        .Where(attr => attr.ConstructorArguments.Length >= 1
                            && attr.ConstructorArguments[0].Value is string)
                        .Select(attr =>
                        {
                            var propName = (string)attr.ConstructorArguments[0].Value!;
                            var propSymbol = type.GetMembers(propName).OfType<IPropertySymbol>().FirstOrDefault();
                            return (propName, propSymbol);
                        })
                        .Where(x => x.propSymbol is not null)
                        .Select(x =>
                        {
                            var ns = type.ContainingNamespace.IsGlobalNamespace
                                ? string.Empty
                                : type.ContainingNamespace.ToDisplayString();

                            return new AssertViaModel(
                                Namespace: ns,
                                OwnerTypeFullName: type.ToDisplayString(),
                                OwnerTypeName: type.Name,
                                PropertyName: x.propName,
                                PropertyTypeFullName: x.propSymbol!.Type.ToDisplayString());
                        });

                    builder.AddRange(viaModels);
                }
            }

            // Assembly-level: [assembly: AssertVia(typeof(T), "PropertyName")]
            foreach (var assembly in EnumerateAssembliesForExternalRules(compilation))
            {
                var viaModels = assembly.GetAttributes()
                    .Where(a => a.AttributeClass?.ToDisplayString() == attrFqn)
                    .Where(attr => attr.ConstructorArguments.Length >= 2
                        && attr.ConstructorArguments[0].Value is ITypeSymbol
                        && attr.ConstructorArguments[1].Value is string)
                    .Select(attr =>
                    {
                        var ownerType = (ITypeSymbol)attr.ConstructorArguments[0].Value!;
                        var propName = (string)attr.ConstructorArguments[1].Value!;
                        var propSymbol = ownerType.GetMembers(propName).OfType<IPropertySymbol>().FirstOrDefault();
                        return (ownerType, propName, propSymbol);
                    })
                    .Where(x => x.propSymbol is not null)
                    .Select(x =>
                    {
                        var ns = x.ownerType.ContainingNamespace is { IsGlobalNamespace: false } ns2
                            ? ns2.ToDisplayString()
                            : string.Empty;

                        return new AssertViaModel(
                            Namespace: ns,
                            OwnerTypeFullName: x.ownerType.ToDisplayString(),
                            OwnerTypeName: x.ownerType.Name,
                            PropertyName: x.propName,
                            PropertyTypeFullName: x.propSymbol!.Type.ToDisplayString());
                    });

                builder.AddRange(viaModels);
            }

            return [.. builder
                .GroupBy(m => (m.OwnerTypeFullName, m.PropertyName))
                .Select(g => g.First())];
        }

        private static void EmitAssertVias(SourceProductionContext spc, ImmutableArray<AssertViaModel> models)
        {
            if (models.IsEmpty)
                return;

            foreach (var model in models)
            {
                EmitAssertViaExtensions(spc, model);
            }
        }

        private static void EmitAssertViaExtensions(SourceProductionContext spc, AssertViaModel model)
        {
            var ownerFq    = $"global::{model.OwnerTypeFullName}";
            var propTypeFq = $"global::{model.PropertyTypeFullName}";
            var safeClassName = $"{model.OwnerTypeName}AssertVia{model.PropertyName}Extensions";

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System.Runtime.CompilerServices;");
            sb.AppendLine("using Catchy;");
            sb.AppendLine("using Catchy.Sdk;");
            sb.AppendLine();

            bool hasNs = !string.IsNullOrEmpty(model.Namespace);
            if (hasNs)
            {
                sb.AppendLine($"namespace {model.Namespace}");
                sb.AppendLine("{");
            }

            AppendGeneratedSummary(sb, 1,
                $"Generated entry-point for {model.OwnerTypeName} that asserts via the {model.PropertyName} property.");
            sb.AppendLine($"    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
            sb.AppendLine($"    public static class {safeClassName}");
            sb.AppendLine("    {");

            AppendGeneratedSummary(sb, 2,
                $"Starts an assertion chain for value by extracting value.{model.PropertyName} as the actual assertion target.");
            sb.AppendLine($"        public static global::Catchy.ValueAssertions<{propTypeFq}> That(");
            sb.AppendLine($"            this global::Catchy.Asserter a,");
            sb.AppendLine($"            {ownerFq} value,");
            sb.AppendLine("            [CallerArgumentExpression(nameof(a))]     string? aExpr   = null,");
            sb.AppendLine("            [CallerArgumentExpression(nameof(value))] string? vExpr   = null,");
            sb.AppendLine("            [CallerFilePath]                          string? file    = null,");
            sb.AppendLine("            [CallerLineNumber]                        int     line    = 0,");
            sb.AppendLine("            [CallerMemberName]                        string? member  = null)");
            sb.AppendLine("        {");
            sb.AppendLine("            var pipeline = a.NewPipeline(asserterExpr: aExpr, methodName: \"That\", valueExpr: vExpr, file: file, line: line, member: member);");
            sb.AppendLine($"            return new global::Catchy.ValueAssertions<{propTypeFq}>(pipeline, value.{model.PropertyName});");
            sb.AppendLine("        }");
            sb.AppendLine("    }");

            if (hasNs)
                sb.AppendLine("}");

            spc.AddSource($"{safeClassName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }
    }
}







