using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Text.RegularExpressions;
using Catchy.Sdk;
using Microsoft.Playwright;

namespace Catchy
{
    public static partial class PwAsserterExtensions
    {
        public static ValueAssertions<ILocator> That(this Asserter a, ILocator value,
            [CallerArgumentExpression(nameof(a))] string? aExpr = null,
            [CallerArgumentExpression(nameof(value))] string? vExpr = null,
            [CallerFilePath] string? file = null,
            [CallerLineNumber] int line = 0,
            [CallerMemberName] string? member = null)
        {
            var p = a.NewPipeline(asserterExpr: aExpr, methodName: "That", valueExpr: vExpr, file: file, line: line, member: member);
            return new ValueAssertions<ILocator>(p, value);
        }
    }

    public static class PwLocatorAssertionsExtensions
    {
        private static SlotContainer Slots(this ValueAssertions<ILocator> assertions) => assertions.GetPipeline().Slots;
        private static Func<bool?> UseInnerTextGetter(this ValueAssertions<ILocator> assertions) => () => assertions.Slots().TryGet(PwSlots.UseInnerText, out bool? value) ? value : null;
        private static Func<float?> ViewportRatioGetter(this ValueAssertions<ILocator> assertions) => () => assertions.Slots().TryGet(PwSlots.ViewportRatio, out float? value) ? value : null;
        private static Func<float?> TimeoutMsGetter(this ValueAssertions<ILocator> assertions) => () => assertions.Slots().TryGet(PwSlots.TimeoutMs, out float? value) ? value : null;
        private static Func<StringComparison> GetEffectiveComparison(this ValueAssertions<ILocator> assertions) => () => assertions.GetPipeline().Settings.DefaultStringComparison;

        public static ValueAssertions<ILocator> WithTimeout(this ValueAssertions<ILocator> assertions, float milliseconds,
            [CallerArgumentExpression(nameof(milliseconds))] string? expr = null)
        { assertions.Slots().Set(PwSlots.TimeoutMs, milliseconds); assertions.Link("WithTimeout", expr); return assertions; }

        public static ValueAssertions<int> Count(this ValueAssertions<ILocator> assertions)
        {
            assertions.Link("Count");
            return new ValueAssertions<int>(assertions.GetPipeline(), assertions.GetValue().CountAsync().GetAwaiter().GetResult());
        }

        public static ValueAssertions<string?> InnerText(this ValueAssertions<ILocator> assertions)
        {
            assertions.Link("InnerText");
            return new ValueAssertions<string?>(assertions.GetPipeline(), assertions.GetValue().InnerTextAsync().GetAwaiter().GetResult());
        }

        public static ValueAssertions<string?> InputValue(this ValueAssertions<ILocator> assertions)
        {
            assertions.Link("InputValue");
            return new ValueAssertions<string?>(assertions.GetPipeline(), assertions.GetValue().InputValueAsync().GetAwaiter().GetResult());
        }

        public static ValueAssertions<string?> TextContent(this ValueAssertions<ILocator> assertions)
        {
            assertions.Link("TextContent");
            return new ValueAssertions<string?>(assertions.GetPipeline(), assertions.GetValue().TextContentAsync().GetAwaiter().GetResult());
        }

        public static ValueAssertions<string?> InnerHtml(this ValueAssertions<ILocator> assertions)
        {
            assertions.Link("InnerHtml");
            return new ValueAssertions<string?>(assertions.GetPipeline(), assertions.GetValue().InnerHTMLAsync().GetAwaiter().GetResult());
        }

        [DebuggerHidden, StackTraceHidden]
        public static ValueAssertions<ILocator> UsingInnerText(this ValueAssertions<ILocator> assertions, bool use = true)
        { assertions.Slots().Set(PwSlots.UseInnerText, use); assertions.Link("UsingInnerText"); return assertions; }

        [DebuggerHidden, StackTraceHidden]
        public static ValueAssertions<ILocator> WithViewportRatio(this ValueAssertions<ILocator> assertions, float ratio,
            [CallerArgumentExpression(nameof(ratio))] string? expr = null)
        { assertions.Slots().Set(PwSlots.ViewportRatio, ratio); assertions.Link("WithViewportRatio", expr); return assertions; }

        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> IsVisible(this ValueAssertions<ILocator> assertions) { assertions.Link("IsVisible"); assertions.Op(a => PwLocatorChecks.IsVisible(assertions.GetValue(), false, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> IsNotVisible(this ValueAssertions<ILocator> assertions) { assertions.Link("IsNotVisible"); assertions.Op(a => PwLocatorChecks.IsVisible(assertions.GetValue(), true, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> IsHidden(this ValueAssertions<ILocator> assertions) { assertions.Link("IsHidden"); assertions.Op(a => PwLocatorChecks.IsHidden(assertions.GetValue(), false, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> IsNotHidden(this ValueAssertions<ILocator> assertions) { assertions.Link("IsNotHidden"); assertions.Op(a => PwLocatorChecks.IsHidden(assertions.GetValue(), true, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> IsAttached(this ValueAssertions<ILocator> assertions) { assertions.Link("IsAttached"); assertions.Op(a => PwLocatorChecks.IsAttached(assertions.GetValue(), false, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> IsNotAttached(this ValueAssertions<ILocator> assertions) { assertions.Link("IsNotAttached"); assertions.Op(a => PwLocatorChecks.IsAttached(assertions.GetValue(), true, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> IsEnabled(this ValueAssertions<ILocator> assertions) { assertions.Link("IsEnabled"); assertions.Op(a => PwLocatorChecks.IsEnabled(assertions.GetValue(), false, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> IsNotEnabled(this ValueAssertions<ILocator> assertions) { assertions.Link("IsNotEnabled"); assertions.Op(a => PwLocatorChecks.IsEnabled(assertions.GetValue(), true, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> IsDisabled(this ValueAssertions<ILocator> assertions) { assertions.Link("IsDisabled"); assertions.Op(a => PwLocatorChecks.IsDisabled(assertions.GetValue(), false, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> IsNotDisabled(this ValueAssertions<ILocator> assertions) { assertions.Link("IsNotDisabled"); assertions.Op(a => PwLocatorChecks.IsDisabled(assertions.GetValue(), true, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> IsEditable(this ValueAssertions<ILocator> assertions) { assertions.Link("IsEditable"); assertions.Op(a => PwLocatorChecks.IsEditable(assertions.GetValue(), false, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> IsNotEditable(this ValueAssertions<ILocator> assertions) { assertions.Link("IsNotEditable"); assertions.Op(a => PwLocatorChecks.IsEditable(assertions.GetValue(), true, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> IsEmpty(this ValueAssertions<ILocator> assertions) { assertions.Link("IsEmpty"); assertions.Op(a => PwLocatorChecks.IsEmpty(assertions.GetValue(), false, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> IsNotEmpty(this ValueAssertions<ILocator> assertions) { assertions.Link("IsNotEmpty"); assertions.Op(a => PwLocatorChecks.IsEmpty(assertions.GetValue(), true, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> IsFocused(this ValueAssertions<ILocator> assertions) { assertions.Link("IsFocused"); assertions.Op(a => PwLocatorChecks.IsFocused(assertions.GetValue(), false, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> IsNotFocused(this ValueAssertions<ILocator> assertions) { assertions.Link("IsNotFocused"); assertions.Op(a => PwLocatorChecks.IsFocused(assertions.GetValue(), true, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> IsRequired(this ValueAssertions<ILocator> assertions) { assertions.Link("IsRequired"); assertions.Op(a => PwLocatorChecks.IsRequired(assertions.GetValue(), false, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> IsNotRequired(this ValueAssertions<ILocator> assertions) { assertions.Link("IsNotRequired"); assertions.Op(a => PwLocatorChecks.IsRequired(assertions.GetValue(), true, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> IsReadonly(this ValueAssertions<ILocator> assertions) { assertions.Link("IsReadonly"); assertions.Op(a => PwLocatorChecks.IsReadonly(assertions.GetValue(), false, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> IsNotReadonly(this ValueAssertions<ILocator> assertions) { assertions.Link("IsNotReadonly"); assertions.Op(a => PwLocatorChecks.IsReadonly(assertions.GetValue(), true, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> IsScrolledToTop(this ValueAssertions<ILocator> assertions) { assertions.Link("IsScrolledToTop"); assertions.Op(a => PwLocatorChecks.IsScrolledToTop(assertions.GetValue(), false, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> IsNotScrolledToTop(this ValueAssertions<ILocator> assertions) { assertions.Link("IsNotScrolledToTop"); assertions.Op(a => PwLocatorChecks.IsScrolledToTop(assertions.GetValue(), true, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> IsScrolledToBottom(this ValueAssertions<ILocator> assertions) { assertions.Link("IsScrolledToBottom"); assertions.Op(a => PwLocatorChecks.IsScrolledToBottom(assertions.GetValue(), false, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> IsNotScrolledToBottom(this ValueAssertions<ILocator> assertions) { assertions.Link("IsNotScrolledToBottom"); assertions.Op(a => PwLocatorChecks.IsScrolledToBottom(assertions.GetValue(), true, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> HasBoundingBox(this ValueAssertions<ILocator> assertions) { assertions.Link("HasBoundingBox"); assertions.Op(a => PwLocatorChecks.HasBoundingBox(assertions.GetValue(), false, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> DoesNotHaveBoundingBox(this ValueAssertions<ILocator> assertions) { assertions.Link("DoesNotHaveBoundingBox"); assertions.Op(a => PwLocatorChecks.HasBoundingBox(assertions.GetValue(), true, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> IsUnique(this ValueAssertions<ILocator> assertions) { assertions.Link("IsUnique"); assertions.Op(a => PwLocatorChecks.IsUnique(assertions.GetValue(), false, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> IsNotUnique(this ValueAssertions<ILocator> assertions) { assertions.Link("IsNotUnique"); assertions.Op(a => PwLocatorChecks.IsUnique(assertions.GetValue(), true, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> IsChecked(this ValueAssertions<ILocator> assertions, bool? checkedValue = null, [CallerArgumentExpression(nameof(checkedValue))] string? expr = null) { assertions.Link("IsChecked", expr); assertions.Op(a => PwLocatorChecks.IsChecked(assertions.GetValue(), false, checkedValue, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> IsNotChecked(this ValueAssertions<ILocator> assertions, bool? checkedValue = null, [CallerArgumentExpression(nameof(checkedValue))] string? expr = null) { assertions.Link("IsNotChecked", expr); assertions.Op(a => PwLocatorChecks.IsChecked(assertions.GetValue(), true, checkedValue, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> IsInViewport(this ValueAssertions<ILocator> assertions) { assertions.Link("IsInViewport"); assertions.Op(a => PwLocatorChecks.IsInViewport(assertions.GetValue(), false, assertions.TimeoutMsGetter(), assertions.ViewportRatioGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> IsNotInViewport(this ValueAssertions<ILocator> assertions) { assertions.Link("IsNotInViewport"); assertions.Op(a => PwLocatorChecks.IsInViewport(assertions.GetValue(), true, assertions.TimeoutMsGetter(), assertions.ViewportRatioGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> HasText(this ValueAssertions<ILocator> assertions, string expected, [CallerArgumentExpression(nameof(expected))] string? e = null) { assertions.Link("HasText", e); assertions.Op(a => PwLocatorChecks.HasText(assertions.GetValue(), expected, false, assertions.GetEffectiveComparison(), assertions.TimeoutMsGetter(), assertions.UseInnerTextGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> HasText(this ValueAssertions<ILocator> assertions, Regex pattern) { assertions.Link("HasText", pattern.ToString()); assertions.Op(a => PwLocatorChecks.HasText(assertions.GetValue(), pattern, false, assertions.TimeoutMsGetter(), assertions.UseInnerTextGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> DoesNotHaveText(this ValueAssertions<ILocator> assertions, string unexpected, [CallerArgumentExpression(nameof(unexpected))] string? e = null) { assertions.Link("DoesNotHaveText", e); assertions.Op(a => PwLocatorChecks.HasText(assertions.GetValue(), unexpected, true, assertions.GetEffectiveComparison(), assertions.TimeoutMsGetter(), assertions.UseInnerTextGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> DoesNotHaveText(this ValueAssertions<ILocator> assertions, Regex pattern) { assertions.Link("DoesNotHaveText", pattern.ToString()); assertions.Op(a => PwLocatorChecks.HasText(assertions.GetValue(), pattern, true, assertions.TimeoutMsGetter(), assertions.UseInnerTextGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> ContainsText(this ValueAssertions<ILocator> assertions, string expected, [CallerArgumentExpression(nameof(expected))] string? e = null) { assertions.Link("ContainsText", e); assertions.Op(a => PwLocatorChecks.ContainsText(assertions.GetValue(), expected, false, assertions.GetEffectiveComparison(), assertions.TimeoutMsGetter(), assertions.UseInnerTextGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> DoesNotContainText(this ValueAssertions<ILocator> assertions, string unexpected, [CallerArgumentExpression(nameof(unexpected))] string? e = null) { assertions.Link("DoesNotContainText", e); assertions.Op(a => PwLocatorChecks.ContainsText(assertions.GetValue(), unexpected, true, assertions.GetEffectiveComparison(), assertions.TimeoutMsGetter(), assertions.UseInnerTextGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> HasText(this ValueAssertions<ILocator> assertions, IEnumerable<string> expected, [CallerArgumentExpression(nameof(expected))] string? e = null) { assertions.Link("HasText", e); assertions.Op(a => PwLocatorChecks.HasText(assertions.GetValue(), expected, false, assertions.GetEffectiveComparison(), assertions.TimeoutMsGetter(), assertions.UseInnerTextGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> DoesNotHaveText(this ValueAssertions<ILocator> assertions, IEnumerable<string> unexpected, [CallerArgumentExpression(nameof(unexpected))] string? e = null) { assertions.Link("DoesNotHaveText", e); assertions.Op(a => PwLocatorChecks.HasText(assertions.GetValue(), unexpected, true, assertions.GetEffectiveComparison(), assertions.TimeoutMsGetter(), assertions.UseInnerTextGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> HasTextInner(this ValueAssertions<ILocator> assertions, string expected, [CallerArgumentExpression(nameof(expected))] string? e = null) => assertions.HasText(expected, e);
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> DoesNotHaveTextInner(this ValueAssertions<ILocator> assertions, string unexpected, [CallerArgumentExpression(nameof(unexpected))] string? e = null) => assertions.DoesNotHaveText(unexpected, e);
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> InnerTextIs(this ValueAssertions<ILocator> assertions, string expected, [CallerArgumentExpression(nameof(expected))] string? expr = null) { assertions.Link("InnerTextIs", expr); assertions.Op(a => PwLocatorChecks.InnerTextIs(assertions.GetValue(), expected, false, assertions.GetEffectiveComparison(), assertions.TimeoutMsGetter(), assertions.IsSkipped(), assertions.GetPipeline())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> InnerTextIsNot(this ValueAssertions<ILocator> assertions, string unexpected, [CallerArgumentExpression(nameof(unexpected))] string? expr = null) { assertions.Link("InnerTextIsNot", expr); assertions.Op(a => PwLocatorChecks.InnerTextIs(assertions.GetValue(), unexpected, true, assertions.GetEffectiveComparison(), assertions.TimeoutMsGetter(), assertions.IsSkipped(), assertions.GetPipeline())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> InnerTextContains(this ValueAssertions<ILocator> assertions, string substring, [CallerArgumentExpression(nameof(substring))] string? expr = null) { assertions.Link("InnerTextContains", expr); assertions.Op(a => PwLocatorChecks.InnerTextContains(assertions.GetValue(), substring, false, assertions.GetEffectiveComparison(), assertions.TimeoutMsGetter(), assertions.IsSkipped(), assertions.GetPipeline())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> InnerTextDoesNotContain(this ValueAssertions<ILocator> assertions, string substring, [CallerArgumentExpression(nameof(substring))] string? expr = null) { assertions.Link("InnerTextDoesNotContain", expr); assertions.Op(a => PwLocatorChecks.InnerTextContains(assertions.GetValue(), substring, true, assertions.GetEffectiveComparison(), assertions.TimeoutMsGetter(), assertions.IsSkipped(), assertions.GetPipeline())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> InnerTextMatches(this ValueAssertions<ILocator> assertions, Regex pattern) { assertions.Link("InnerTextMatches", pattern.ToString()); assertions.Op(a => PwLocatorChecks.InnerTextMatches(assertions.GetValue(), pattern, false, assertions.TimeoutMsGetter(), assertions.IsSkipped(), assertions.GetPipeline())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> InnerTextDoesNotMatch(this ValueAssertions<ILocator> assertions, Regex pattern) { assertions.Link("InnerTextDoesNotMatch", pattern.ToString()); assertions.Op(a => PwLocatorChecks.InnerTextMatches(assertions.GetValue(), pattern, true, assertions.TimeoutMsGetter(), assertions.IsSkipped(), assertions.GetPipeline())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> InputValueIs(this ValueAssertions<ILocator> assertions, string expected, [CallerArgumentExpression(nameof(expected))] string? expr = null) { assertions.Link("InputValueIs", expr); assertions.Op(a => PwLocatorChecks.InputValueIs(assertions.GetValue(), expected, false, assertions.GetEffectiveComparison(), assertions.TimeoutMsGetter(), assertions.IsSkipped(), assertions.GetPipeline())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> InputValueIsNot(this ValueAssertions<ILocator> assertions, string unexpected, [CallerArgumentExpression(nameof(unexpected))] string? expr = null) { assertions.Link("InputValueIsNot", expr); assertions.Op(a => PwLocatorChecks.InputValueIs(assertions.GetValue(), unexpected, true, assertions.GetEffectiveComparison(), assertions.TimeoutMsGetter(), assertions.IsSkipped(), assertions.GetPipeline())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> InputValueContains(this ValueAssertions<ILocator> assertions, string substring, [CallerArgumentExpression(nameof(substring))] string? expr = null) { assertions.Link("InputValueContains", expr); assertions.Op(a => PwLocatorChecks.InputValueContains(assertions.GetValue(), substring, false, assertions.GetEffectiveComparison(), assertions.TimeoutMsGetter(), assertions.IsSkipped(), assertions.GetPipeline())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> InputValueDoesNotContain(this ValueAssertions<ILocator> assertions, string substring, [CallerArgumentExpression(nameof(substring))] string? expr = null) { assertions.Link("InputValueDoesNotContain", expr); assertions.Op(a => PwLocatorChecks.InputValueContains(assertions.GetValue(), substring, true, assertions.GetEffectiveComparison(), assertions.TimeoutMsGetter(), assertions.IsSkipped(), assertions.GetPipeline())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> InputValueMatches(this ValueAssertions<ILocator> assertions, Regex pattern) { assertions.Link("InputValueMatches", pattern.ToString()); assertions.Op(a => PwLocatorChecks.InputValueMatches(assertions.GetValue(), pattern, false, assertions.TimeoutMsGetter(), assertions.IsSkipped(), assertions.GetPipeline())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> InputValueDoesNotMatch(this ValueAssertions<ILocator> assertions, Regex pattern) { assertions.Link("InputValueDoesNotMatch", pattern.ToString()); assertions.Op(a => PwLocatorChecks.InputValueMatches(assertions.GetValue(), pattern, true, assertions.TimeoutMsGetter(), assertions.IsSkipped(), assertions.GetPipeline())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> TextContentIs(this ValueAssertions<ILocator> assertions, string expected, [CallerArgumentExpression(nameof(expected))] string? expr = null) { assertions.Link("TextContentIs", expr); assertions.Op(a => PwLocatorChecks.TextContentIs(assertions.GetValue(), expected, false, assertions.GetEffectiveComparison(), assertions.TimeoutMsGetter(), assertions.IsSkipped(), assertions.GetPipeline())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> TextContentIsNot(this ValueAssertions<ILocator> assertions, string unexpected, [CallerArgumentExpression(nameof(unexpected))] string? expr = null) { assertions.Link("TextContentIsNot", expr); assertions.Op(a => PwLocatorChecks.TextContentIs(assertions.GetValue(), unexpected, true, assertions.GetEffectiveComparison(), assertions.TimeoutMsGetter(), assertions.IsSkipped(), assertions.GetPipeline())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> TextContentContains(this ValueAssertions<ILocator> assertions, string substring, [CallerArgumentExpression(nameof(substring))] string? expr = null) { assertions.Link("TextContentContains", expr); assertions.Op(a => PwLocatorChecks.TextContentContains(assertions.GetValue(), substring, false, assertions.GetEffectiveComparison(), assertions.TimeoutMsGetter(), assertions.IsSkipped(), assertions.GetPipeline())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> TextContentDoesNotContain(this ValueAssertions<ILocator> assertions, string substring, [CallerArgumentExpression(nameof(substring))] string? expr = null) { assertions.Link("TextContentDoesNotContain", expr); assertions.Op(a => PwLocatorChecks.TextContentContains(assertions.GetValue(), substring, true, assertions.GetEffectiveComparison(), assertions.TimeoutMsGetter(), assertions.IsSkipped(), assertions.GetPipeline())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> InnerHtmlContains(this ValueAssertions<ILocator> assertions, string substring, [CallerArgumentExpression(nameof(substring))] string? expr = null) { assertions.Link("InnerHtmlContains", expr); assertions.Op(a => PwLocatorChecks.InnerHtmlContains(assertions.GetValue(), substring, false, assertions.GetEffectiveComparison(), assertions.TimeoutMsGetter(), assertions.IsSkipped(), assertions.GetPipeline())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> InnerHtmlDoesNotContain(this ValueAssertions<ILocator> assertions, string substring, [CallerArgumentExpression(nameof(substring))] string? expr = null) { assertions.Link("InnerHtmlDoesNotContain", expr); assertions.Op(a => PwLocatorChecks.InnerHtmlContains(assertions.GetValue(), substring, true, assertions.GetEffectiveComparison(), assertions.TimeoutMsGetter(), assertions.IsSkipped(), assertions.GetPipeline())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> HasAttribute(this ValueAssertions<ILocator> assertions, string name, string value, [CallerArgumentExpression(nameof(name))] string? nE = null, [CallerArgumentExpression(nameof(value))] string? vE = null) { assertions.Link("HasAttribute", nE, vE); assertions.Op(a => PwLocatorChecks.HasAttribute(assertions.GetValue(), name, value, false, assertions.GetEffectiveComparison(), assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> HasAttribute(this ValueAssertions<ILocator> assertions, string name, Regex pattern, [CallerArgumentExpression(nameof(name))] string? nE = null) { assertions.Link("HasAttribute", nE, pattern.ToString()); assertions.Op(a => PwLocatorChecks.HasAttribute(assertions.GetValue(), name, pattern, false, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> DoesNotHaveAttribute(this ValueAssertions<ILocator> assertions, string name, string value, [CallerArgumentExpression(nameof(name))] string? nE = null, [CallerArgumentExpression(nameof(value))] string? vE = null) { assertions.Link("DoesNotHaveAttribute", nE, vE); assertions.Op(a => PwLocatorChecks.HasAttribute(assertions.GetValue(), name, value, true, assertions.GetEffectiveComparison(), assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> DoesNotHaveAttribute(this ValueAssertions<ILocator> assertions, string name, Regex pattern, [CallerArgumentExpression(nameof(name))] string? nE = null) { assertions.Link("DoesNotHaveAttribute", nE, pattern.ToString()); assertions.Op(a => PwLocatorChecks.HasAttribute(assertions.GetValue(), name, pattern, true, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> HasAttributePresent(this ValueAssertions<ILocator> assertions, string name, [CallerArgumentExpression(nameof(name))] string? expr = null) { assertions.Link("HasAttributePresent", expr); assertions.Op(a => PwLocatorChecks.AttributePresent(assertions.GetValue(), name, false, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> DoesNotHaveAttributePresent(this ValueAssertions<ILocator> assertions, string name, [CallerArgumentExpression(nameof(name))] string? expr = null) { assertions.Link("DoesNotHaveAttributePresent", expr); assertions.Op(a => PwLocatorChecks.AttributePresent(assertions.GetValue(), name, true, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> HasHref(this ValueAssertions<ILocator> assertions, string url, [CallerArgumentExpression(nameof(url))] string? e = null) { assertions.Link("HasHref", e); assertions.Op(a => PwLocatorChecks.HasAttribute(assertions.GetValue(), "href", url, false, assertions.GetEffectiveComparison(), assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> HasHref(this ValueAssertions<ILocator> assertions, Regex p) { assertions.Link("HasHref", p.ToString()); assertions.Op(a => PwLocatorChecks.HasAttribute(assertions.GetValue(), "href", p, false, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> DoesNotHaveHref(this ValueAssertions<ILocator> assertions, string url, [CallerArgumentExpression(nameof(url))] string? e = null) { assertions.Link("DoesNotHaveHref", e); assertions.Op(a => PwLocatorChecks.HasAttribute(assertions.GetValue(), "href", url, true, assertions.GetEffectiveComparison(), assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> DoesNotHaveHref(this ValueAssertions<ILocator> assertions, Regex p) { assertions.Link("DoesNotHaveHref", p.ToString()); assertions.Op(a => PwLocatorChecks.HasAttribute(assertions.GetValue(), "href", p, true, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> HasSrc(this ValueAssertions<ILocator> assertions, string url, [CallerArgumentExpression(nameof(url))] string? e = null) { assertions.Link("HasSrc", e); assertions.Op(a => PwLocatorChecks.HasAttribute(assertions.GetValue(), "src", url, false, assertions.GetEffectiveComparison(), assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> DoesNotHaveSrc(this ValueAssertions<ILocator> assertions, string url, [CallerArgumentExpression(nameof(url))] string? e = null) { assertions.Link("DoesNotHaveSrc", e); assertions.Op(a => PwLocatorChecks.HasAttribute(assertions.GetValue(), "src", url, true, assertions.GetEffectiveComparison(), assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> HasAlt(this ValueAssertions<ILocator> assertions, string text, [CallerArgumentExpression(nameof(text))] string? e = null) { assertions.Link("HasAlt", e); assertions.Op(a => PwLocatorChecks.HasAttribute(assertions.GetValue(), "alt", text, false, assertions.GetEffectiveComparison(), assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> DoesNotHaveAlt(this ValueAssertions<ILocator> assertions, string text, [CallerArgumentExpression(nameof(text))] string? e = null) { assertions.Link("DoesNotHaveAlt", e); assertions.Op(a => PwLocatorChecks.HasAttribute(assertions.GetValue(), "alt", text, true, assertions.GetEffectiveComparison(), assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> HasPlaceholder(this ValueAssertions<ILocator> assertions, string text, [CallerArgumentExpression(nameof(text))] string? e = null) { assertions.Link("HasPlaceholder", e); assertions.Op(a => PwLocatorChecks.HasAttribute(assertions.GetValue(), "placeholder", text, false, assertions.GetEffectiveComparison(), assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> DoesNotHavePlaceholder(this ValueAssertions<ILocator> assertions, string text, [CallerArgumentExpression(nameof(text))] string? e = null) { assertions.Link("DoesNotHavePlaceholder", e); assertions.Op(a => PwLocatorChecks.HasAttribute(assertions.GetValue(), "placeholder", text, true, assertions.GetEffectiveComparison(), assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> HasInputType(this ValueAssertions<ILocator> assertions, string type, [CallerArgumentExpression(nameof(type))] string? e = null) { assertions.Link("HasInputType", e); assertions.Op(a => PwLocatorChecks.HasAttribute(assertions.GetValue(), "type", type, false, assertions.GetEffectiveComparison(), assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> DoesNotHaveInputType(this ValueAssertions<ILocator> assertions, string type, [CallerArgumentExpression(nameof(type))] string? e = null) { assertions.Link("DoesNotHaveInputType", e); assertions.Op(a => PwLocatorChecks.HasAttribute(assertions.GetValue(), "type", type, true, assertions.GetEffectiveComparison(), assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> HasNameAttribute(this ValueAssertions<ILocator> assertions, string name, [CallerArgumentExpression(nameof(name))] string? e = null) { assertions.Link("HasNameAttribute", e); assertions.Op(a => PwLocatorChecks.HasAttribute(assertions.GetValue(), "name", name, false, assertions.GetEffectiveComparison(), assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> DoesNotHaveNameAttribute(this ValueAssertions<ILocator> assertions, string name, [CallerArgumentExpression(nameof(name))] string? e = null) { assertions.Link("DoesNotHaveNameAttribute", e); assertions.Op(a => PwLocatorChecks.HasAttribute(assertions.GetValue(), "name", name, true, assertions.GetEffectiveComparison(), assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> HasClass(this ValueAssertions<ILocator> assertions, string expected, [CallerArgumentExpression(nameof(expected))] string? e = null) { assertions.Link("HasClass", e); assertions.Op(a => PwLocatorChecks.HasClass(assertions.GetValue(), expected, false, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> HasClass(this ValueAssertions<ILocator> assertions, Regex p) { assertions.Link("HasClass", p.ToString()); assertions.Op(a => PwLocatorChecks.HasClass(assertions.GetValue(), p, false, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> DoesNotHaveClass(this ValueAssertions<ILocator> assertions, string unexpected, [CallerArgumentExpression(nameof(unexpected))] string? e = null) { assertions.Link("DoesNotHaveClass", e); assertions.Op(a => PwLocatorChecks.HasClass(assertions.GetValue(), unexpected, true, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> DoesNotHaveClass(this ValueAssertions<ILocator> assertions, Regex p) { assertions.Link("DoesNotHaveClass", p.ToString()); assertions.Op(a => PwLocatorChecks.HasClass(assertions.GetValue(), p, true, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> ContainsClass(this ValueAssertions<ILocator> assertions, string className, [CallerArgumentExpression(nameof(className))] string? e = null) { assertions.Link("ContainsClass", e); assertions.Op(a => PwLocatorChecks.ContainsClass(assertions.GetValue(), className, false, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> DoesNotContainClass(this ValueAssertions<ILocator> assertions, string className, [CallerArgumentExpression(nameof(className))] string? e = null) { assertions.Link("DoesNotContainClass", e); assertions.Op(a => PwLocatorChecks.ContainsClass(assertions.GetValue(), className, true, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> HasCss(this ValueAssertions<ILocator> assertions, string name, string value, [CallerArgumentExpression(nameof(name))] string? nE = null, [CallerArgumentExpression(nameof(value))] string? vE = null) { assertions.Link("HasCss", nE, vE); assertions.Op(a => PwLocatorChecks.HasCss(assertions.GetValue(), name, value, false, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> DoesNotHaveCss(this ValueAssertions<ILocator> assertions, string name, string value, [CallerArgumentExpression(nameof(name))] string? nE = null, [CallerArgumentExpression(nameof(value))] string? vE = null) { assertions.Link("DoesNotHaveCss", nE, vE); assertions.Op(a => PwLocatorChecks.HasCss(assertions.GetValue(), name, value, true, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> HasCss(this ValueAssertions<ILocator> assertions, string name, Regex p, [CallerArgumentExpression(nameof(name))] string? nE = null) { assertions.Link("HasCss", nE, p.ToString()); assertions.Op(a => PwLocatorChecks.HasCss(assertions.GetValue(), name, p, false, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> DoesNotHaveCss(this ValueAssertions<ILocator> assertions, string name, Regex p, [CallerArgumentExpression(nameof(name))] string? nE = null) { assertions.Link("DoesNotHaveCss", nE, p.ToString()); assertions.Op(a => PwLocatorChecks.HasCss(assertions.GetValue(), name, p, true, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> HasId(this ValueAssertions<ILocator> assertions, string id, [CallerArgumentExpression(nameof(id))] string? e = null) { assertions.Link("HasId", e); assertions.Op(a => PwLocatorChecks.HasId(assertions.GetValue(), id, false, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> DoesNotHaveId(this ValueAssertions<ILocator> assertions, string id, [CallerArgumentExpression(nameof(id))] string? e = null) { assertions.Link("DoesNotHaveId", e); assertions.Op(a => PwLocatorChecks.HasId(assertions.GetValue(), id, true, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> HasId(this ValueAssertions<ILocator> assertions, Regex p) { assertions.Link("HasId", p.ToString()); assertions.Op(a => PwLocatorChecks.HasId(assertions.GetValue(), p, false, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> DoesNotHaveId(this ValueAssertions<ILocator> assertions, Regex p) { assertions.Link("DoesNotHaveId", p.ToString()); assertions.Op(a => PwLocatorChecks.HasId(assertions.GetValue(), p, true, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> HasCount(this ValueAssertions<ILocator> assertions, int count, [CallerArgumentExpression(nameof(count))] string? e = null) { assertions.Link("HasCount", e); assertions.Op(a => PwLocatorChecks.HasCount(assertions.GetValue(), count, false, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> DoesNotHaveCount(this ValueAssertions<ILocator> assertions, int count, [CallerArgumentExpression(nameof(count))] string? e = null) { assertions.Link("DoesNotHaveCount", e); assertions.Op(a => PwLocatorChecks.HasCount(assertions.GetValue(), count, true, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> CountGreaterThan(this ValueAssertions<ILocator> assertions, int count, [CallerArgumentExpression(nameof(count))] string? e = null) { assertions.Link("CountGreaterThan", e); assertions.Op(a => PwLocatorChecks.CountGreaterThan(assertions.GetValue(), count, false, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> CountGreaterThanOrEqual(this ValueAssertions<ILocator> assertions, int count, [CallerArgumentExpression(nameof(count))] string? e = null) { assertions.Link("CountGreaterThanOrEqual", e); assertions.Op(a => PwLocatorChecks.CountGreaterThanOrEqual(assertions.GetValue(), count, false, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> CountNotGreaterThan(this ValueAssertions<ILocator> assertions, int count, [CallerArgumentExpression(nameof(count))] string? e = null) { assertions.Link("CountNotGreaterThan", e); assertions.Op(a => PwLocatorChecks.CountGreaterThan(assertions.GetValue(), count, true, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> CountLessThan(this ValueAssertions<ILocator> assertions, int count, [CallerArgumentExpression(nameof(count))] string? e = null) { assertions.Link("CountLessThan", e); assertions.Op(a => PwLocatorChecks.CountLessThan(assertions.GetValue(), count, false, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> CountNotLessThan(this ValueAssertions<ILocator> assertions, int count, [CallerArgumentExpression(nameof(count))] string? e = null) { assertions.Link("CountNotLessThan", e); assertions.Op(a => PwLocatorChecks.CountLessThan(assertions.GetValue(), count, true, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> CountInRange(this ValueAssertions<ILocator> assertions, int min, int max, [CallerArgumentExpression(nameof(min))] string? minE = null, [CallerArgumentExpression(nameof(max))] string? maxE = null) { assertions.Link("CountInRange", minE, maxE); assertions.Op(a => PwLocatorChecks.CountInRange(assertions.GetValue(), min, max, false, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> CountNotInRange(this ValueAssertions<ILocator> assertions, int min, int max, [CallerArgumentExpression(nameof(min))] string? minE = null, [CallerArgumentExpression(nameof(max))] string? maxE = null) { assertions.Link("CountNotInRange", minE, maxE); assertions.Op(a => PwLocatorChecks.CountInRange(assertions.GetValue(), min, max, true, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> HasValue(this ValueAssertions<ILocator> assertions, string value, [CallerArgumentExpression(nameof(value))] string? e = null) { assertions.Link("HasValue", e); assertions.Op(a => PwLocatorChecks.HasValue(assertions.GetValue(), value, false, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> DoesNotHaveValue(this ValueAssertions<ILocator> assertions, string value, [CallerArgumentExpression(nameof(value))] string? e = null) { assertions.Link("DoesNotHaveValue", e); assertions.Op(a => PwLocatorChecks.HasValue(assertions.GetValue(), value, true, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        /// <summary>Asserts that locator value matches pattern <paramref name="p"/>.</summary>
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> HasValue(this ValueAssertions<ILocator> assertions, Regex p) { assertions.Link("HasValue", p.ToString()); assertions.Op(a => PwLocatorChecks.HasValue(assertions.GetValue(), p, false, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        /// <summary>Asserts that locator value does not match pattern <paramref name="p"/>.</summary>
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> DoesNotHaveValue(this ValueAssertions<ILocator> assertions, Regex p) { assertions.Link("DoesNotHaveValue", p.ToString()); assertions.Op(a => PwLocatorChecks.HasValue(assertions.GetValue(), p, true, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        /// <summary>Asserts that locator values equal <paramref name="values"/>.</summary>
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> HasValues(this ValueAssertions<ILocator> assertions, IEnumerable<string> values, [CallerArgumentExpression(nameof(values))] string? e = null) { assertions.Link("HasValues", e); assertions.Op(a => PwLocatorChecks.HasValues(assertions.GetValue(), values, false, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        /// <summary>Asserts that locator values do not equal <paramref name="values"/>.</summary>
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> DoesNotHaveValues(this ValueAssertions<ILocator> assertions, IEnumerable<string> values, [CallerArgumentExpression(nameof(values))] string? e = null) { assertions.Link("DoesNotHaveValues", e); assertions.Op(a => PwLocatorChecks.HasValues(assertions.GetValue(), values, true, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        /// <summary>Asserts that JS property <paramref name="name"/> equals <paramref name="value"/>.</summary>
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> HasJsProperty(this ValueAssertions<ILocator> assertions, string name, object value, [CallerArgumentExpression(nameof(name))] string? nE = null, [CallerArgumentExpression(nameof(value))] string? vE = null) { assertions.Link("HasJsProperty", nE, vE); assertions.Op(a => PwLocatorChecks.HasJsProperty(assertions.GetValue(), name, value, false, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        /// <summary>Asserts that JS property <paramref name="name"/> does not equal <paramref name="value"/>.</summary>
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> DoesNotHaveJsProperty(this ValueAssertions<ILocator> assertions, string name, object value, [CallerArgumentExpression(nameof(name))] string? nE = null, [CallerArgumentExpression(nameof(value))] string? vE = null) { assertions.Link("DoesNotHaveJsProperty", nE, vE); assertions.Op(a => PwLocatorChecks.HasJsProperty(assertions.GetValue(), name, value, true, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        /// <summary>Asserts that accessible name equals <paramref name="expected"/>.</summary>
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> HasAccessibleName(this ValueAssertions<ILocator> assertions, string expected, [CallerArgumentExpression(nameof(expected))] string? e = null) { assertions.Link("HasAccessibleName", e); assertions.Op(a => PwLocatorChecks.HasAccessibleName(assertions.GetValue(), expected, false, assertions.GetEffectiveComparison(), assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        /// <summary>Asserts that accessible name does not equal <paramref name="unexpected"/>.</summary>
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> DoesNotHaveAccessibleName(this ValueAssertions<ILocator> assertions, string unexpected, [CallerArgumentExpression(nameof(unexpected))] string? e = null) { assertions.Link("DoesNotHaveAccessibleName", e); assertions.Op(a => PwLocatorChecks.HasAccessibleName(assertions.GetValue(), unexpected, true, assertions.GetEffectiveComparison(), assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        /// <summary>Asserts that accessible name matches pattern <paramref name="p"/>.</summary>
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> HasAccessibleName(this ValueAssertions<ILocator> assertions, Regex p) { assertions.Link("HasAccessibleName", p.ToString()); assertions.Op(a => PwLocatorChecks.HasAccessibleName(assertions.GetValue(), p, false, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        /// <summary>Asserts that accessible name does not match pattern <paramref name="p"/>.</summary>
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> DoesNotHaveAccessibleName(this ValueAssertions<ILocator> assertions, Regex p) { assertions.Link("DoesNotHaveAccessibleName", p.ToString()); assertions.Op(a => PwLocatorChecks.HasAccessibleName(assertions.GetValue(), p, true, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        /// <summary>Asserts that accessible description equals <paramref name="expected"/>.</summary>
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> HasAccessibleDescription(this ValueAssertions<ILocator> assertions, string expected, [CallerArgumentExpression(nameof(expected))] string? e = null) { assertions.Link("HasAccessibleDescription", e); assertions.Op(a => PwLocatorChecks.HasAccessibleDescription(assertions.GetValue(), expected, false, assertions.GetEffectiveComparison(), assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        /// <summary>Asserts that accessible description does not equal <paramref name="unexpected"/>.</summary>
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> DoesNotHaveAccessibleDescription(this ValueAssertions<ILocator> assertions, string unexpected, [CallerArgumentExpression(nameof(unexpected))] string? e = null) { assertions.Link("DoesNotHaveAccessibleDescription", e); assertions.Op(a => PwLocatorChecks.HasAccessibleDescription(assertions.GetValue(), unexpected, true, assertions.GetEffectiveComparison(), assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        /// <summary>Asserts that accessible description matches pattern <paramref name="p"/>.</summary>
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> HasAccessibleDescription(this ValueAssertions<ILocator> assertions, Regex p) { assertions.Link("HasAccessibleDescription", p.ToString()); assertions.Op(a => PwLocatorChecks.HasAccessibleDescription(assertions.GetValue(), p, false, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        /// <summary>Asserts that accessible description does not match pattern <paramref name="p"/>.</summary>
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> DoesNotHaveAccessibleDescription(this ValueAssertions<ILocator> assertions, Regex p) { assertions.Link("DoesNotHaveAccessibleDescription", p.ToString()); assertions.Op(a => PwLocatorChecks.HasAccessibleDescription(assertions.GetValue(), p, true, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> HasAccessibleErrorMessage(this ValueAssertions<ILocator> assertions, string msg, [CallerArgumentExpression(nameof(msg))] string? e = null) { assertions.Link("HasAccessibleErrorMessage", e); assertions.Op(a => PwLocatorChecks.HasAccessibleErrorMessage(assertions.GetValue(), msg, false, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> DoesNotHaveAccessibleErrorMessage(this ValueAssertions<ILocator> assertions, string msg, [CallerArgumentExpression(nameof(msg))] string? e = null) { assertions.Link("DoesNotHaveAccessibleErrorMessage", e); assertions.Op(a => PwLocatorChecks.HasAccessibleErrorMessage(assertions.GetValue(), msg, true, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> HasRole(this ValueAssertions<ILocator> assertions, AriaRole role) { assertions.Link("HasRole", role.ToString()); assertions.Op(a => PwLocatorChecks.HasRole(assertions.GetValue(), role, false, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> DoesNotHaveRole(this ValueAssertions<ILocator> assertions, AriaRole role) { assertions.Link("DoesNotHaveRole", role.ToString()); assertions.Op(a => PwLocatorChecks.HasRole(assertions.GetValue(), role, true, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> MatchesAriaSnapshot(this ValueAssertions<ILocator> assertions, string template, [CallerArgumentExpression(nameof(template))] string? e = null) { assertions.Link("MatchesAriaSnapshot", e); assertions.Op(a => PwLocatorChecks.MatchesAriaSnapshot(assertions.GetValue(), template, false, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> DoesNotMatchAriaSnapshot(this ValueAssertions<ILocator> assertions, string template, [CallerArgumentExpression(nameof(template))] string? e = null) { assertions.Link("DoesNotMatchAriaSnapshot", e); assertions.Op(a => PwLocatorChecks.MatchesAriaSnapshot(assertions.GetValue(), template, true, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        /// <summary>Asserts that locator width equals <paramref name="width"/> within <paramref name="tolerance"/>.</summary>
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> HasWidth(this ValueAssertions<ILocator> assertions, float width, float tolerance = 0f, [CallerArgumentExpression(nameof(width))] string? e = null) { assertions.Link("HasWidth", e); assertions.Op(a => PwLocatorChecks.HasWidth(assertions.GetValue(), width, tolerance, false, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        /// <summary>Asserts that locator width does not equal <paramref name="width"/> within <paramref name="tolerance"/>.</summary>
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> DoesNotHaveWidth(this ValueAssertions<ILocator> assertions, float width, float tolerance = 0f, [CallerArgumentExpression(nameof(width))] string? e = null) { assertions.Link("DoesNotHaveWidth", e); assertions.Op(a => PwLocatorChecks.HasWidth(assertions.GetValue(), width, tolerance, true, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        /// <summary>Asserts that locator height equals <paramref name="height"/> within <paramref name="tolerance"/>.</summary>
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> HasHeight(this ValueAssertions<ILocator> assertions, float height, float tolerance = 0f, [CallerArgumentExpression(nameof(height))] string? e = null) { assertions.Link("HasHeight", e); assertions.Op(a => PwLocatorChecks.HasHeight(assertions.GetValue(), height, tolerance, false, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        /// <summary>Asserts that locator height does not equal <paramref name="height"/> within <paramref name="tolerance"/>.</summary>
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> DoesNotHaveHeight(this ValueAssertions<ILocator> assertions, float height, float tolerance = 0f, [CallerArgumentExpression(nameof(height))] string? e = null) { assertions.Link("DoesNotHaveHeight", e); assertions.Op(a => PwLocatorChecks.HasHeight(assertions.GetValue(), height, tolerance, true, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        /// <summary>Asserts that JavaScript <paramref name="expression"/> evaluates to truthy.</summary>
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> EvalIsTruthy(this ValueAssertions<ILocator> assertions, string expression, [CallerArgumentExpression(nameof(expression))] string? e = null) { assertions.Link("EvalIsTruthy", e); assertions.Op(a => PwLocatorChecks.EvalIsTruthy(assertions.GetValue(), expression, false, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        /// <summary>Asserts that JavaScript <paramref name="expression"/> evaluates to falsy.</summary>
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> EvalIsFalsy(this ValueAssertions<ILocator> assertions, string expression, [CallerArgumentExpression(nameof(expression))] string? e = null) { assertions.Link("EvalIsFalsy", e); assertions.Op(a => PwLocatorChecks.EvalIsTruthy(assertions.GetValue(), expression, true, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        /// <summary>Asserts that JavaScript <paramref name="expression"/> equals <paramref name="expected"/>.</summary>
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> EvalIs(this ValueAssertions<ILocator> assertions, string expression, string expected, [CallerArgumentExpression(nameof(expression))] string? exprE = null, [CallerArgumentExpression(nameof(expected))] string? expE = null) { assertions.Link("EvalIs", exprE, expE); assertions.Op(a => PwLocatorChecks.EvalIs(assertions.GetValue(), expression, expected, false, assertions.GetEffectiveComparison(), assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        /// <summary>Asserts that JavaScript <paramref name="expression"/> does not equal <paramref name="unexpected"/>.</summary>
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> EvalIsNot(this ValueAssertions<ILocator> assertions, string expression, string unexpected, [CallerArgumentExpression(nameof(expression))] string? exprE = null, [CallerArgumentExpression(nameof(unexpected))] string? expE = null) { assertions.Link("EvalIsNot", exprE, expE); assertions.Op(a => PwLocatorChecks.EvalIs(assertions.GetValue(), expression, unexpected, true, assertions.GetEffectiveComparison(), assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        /// <summary>Asserts that computed style <paramref name="property"/> equals <paramref name="value"/>.</summary>
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> HasComputedStyle(this ValueAssertions<ILocator> assertions, string property, string value, [CallerArgumentExpression(nameof(property))] string? pE = null, [CallerArgumentExpression(nameof(value))] string? vE = null) { assertions.Link("HasComputedStyle", pE, vE); assertions.Op(a => PwLocatorChecks.HasComputedStyle(assertions.GetValue(), property, value, false, assertions.GetEffectiveComparison(), assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        /// <summary>Asserts that computed style <paramref name="property"/> does not equal <paramref name="value"/>.</summary>
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> DoesNotHaveComputedStyle(this ValueAssertions<ILocator> assertions, string property, string value, [CallerArgumentExpression(nameof(property))] string? pE = null, [CallerArgumentExpression(nameof(value))] string? vE = null) { assertions.Link("DoesNotHaveComputedStyle", pE, vE); assertions.Op(a => PwLocatorChecks.HasComputedStyle(assertions.GetValue(), property, value, true, assertions.GetEffectiveComparison(), assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        /// <summary>Asserts that locator opacity equals <paramref name="opacity"/> within <paramref name="tolerance"/>.</summary>
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> HasOpacity(this ValueAssertions<ILocator> assertions, double opacity, double tolerance = 0.01, [CallerArgumentExpression(nameof(opacity))] string? e = null) { assertions.Link("HasOpacity", e); assertions.Op(a => PwLocatorChecks.HasOpacity(assertions.GetValue(), opacity, tolerance, false, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        /// <summary>Asserts that locator opacity does not equal <paramref name="opacity"/> within <paramref name="tolerance"/>.</summary>
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> DoesNotHaveOpacity(this ValueAssertions<ILocator> assertions, double opacity, double tolerance = 0.01, [CallerArgumentExpression(nameof(opacity))] string? e = null) { assertions.Link("DoesNotHaveOpacity", e); assertions.Op(a => PwLocatorChecks.HasOpacity(assertions.GetValue(), opacity, tolerance, true, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        /// <summary>Asserts that selected option equals <paramref name="textOrValue"/>.</summary>
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> HasSelectedOption(this ValueAssertions<ILocator> assertions, string textOrValue, [CallerArgumentExpression(nameof(textOrValue))] string? e = null) { assertions.Link("HasSelectedOption", e); assertions.Op(a => PwLocatorChecks.HasSelectedOption(assertions.GetValue(), textOrValue, false, assertions.GetEffectiveComparison(), assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        /// <summary>Asserts that selected option does not equal <paramref name="textOrValue"/>.</summary>
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> DoesNotHaveSelectedOption(this ValueAssertions<ILocator> assertions, string textOrValue, [CallerArgumentExpression(nameof(textOrValue))] string? e = null) { assertions.Link("DoesNotHaveSelectedOption", e); assertions.Op(a => PwLocatorChecks.HasSelectedOption(assertions.GetValue(), textOrValue, true, assertions.GetEffectiveComparison(), assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        /// <summary>Asserts that max length equals <paramref name="length"/>.</summary>
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> HasMaxLength(this ValueAssertions<ILocator> assertions, int length, [CallerArgumentExpression(nameof(length))] string? e = null) { assertions.Link("HasMaxLength", e); assertions.Op(a => PwLocatorChecks.HasMaxLength(assertions.GetValue(), length, false, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        /// <summary>Asserts that max length does not equal <paramref name="length"/>.</summary>
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> DoesNotHaveMaxLength(this ValueAssertions<ILocator> assertions, int length, [CallerArgumentExpression(nameof(length))] string? e = null) { assertions.Link("DoesNotHaveMaxLength", e); assertions.Op(a => PwLocatorChecks.HasMaxLength(assertions.GetValue(), length, true, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        /// <summary>Asserts that tab index equals <paramref name="index"/>.</summary>
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> HasTabIndex(this ValueAssertions<ILocator> assertions, int index, [CallerArgumentExpression(nameof(index))] string? e = null) { assertions.Link("HasTabIndex", e); assertions.Op(a => PwLocatorChecks.HasTabIndex(assertions.GetValue(), index, false, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
        /// <summary>Asserts that tab index does not equal <paramref name="index"/>.</summary>
        [DebuggerHidden, StackTraceHidden, AssertionMethod] public static ValueAssertions<ILocator> DoesNotHaveTabIndex(this ValueAssertions<ILocator> assertions, int index, [CallerArgumentExpression(nameof(index))] string? e = null) { assertions.Link("DoesNotHaveTabIndex", e); assertions.Op(a => PwLocatorChecks.HasTabIndex(assertions.GetValue(), index, true, assertions.TimeoutMsGetter(), assertions.IsSkipped())); return assertions; }
    }
}


