<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>netstandard2.0;net5.0;net6.0;net7.0;net8.0;net9.0</TargetFrameworks>
		<LangVersion>14</LangVersion>
		<Nullable>enable</Nullable>
		<ImplicitUsings>disable</ImplicitUsings>
		<AllowUnsafeBlocks>false</AllowUnsafeBlocks>
		<AssemblyName>Catchy.MSTest</AssemblyName>
		<RootNamespace>Catchy.MSTest</RootNamespace>
		<PackageId>Catchy.MSTest</PackageId>
		<Description>Catchy integration package for MSTest with async-native fluent assertion support.</Description>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="MSTest.TestFramework" Version="4.3.3" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Catchy\Catchy.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <None Include="README.md" Pack="true" PackagePath="\" />
	</ItemGroup>

</Project>
